### ISSUE TITLE
[BUG] InternalExecutionError even /* sfge-disable-stack ApexFlsViolationRule */ were assigned

### ISSUE THREAD

**Issue by oldgunner** [forcedotcom/sfdx-scanner#1181] opened 2023-09-18 09:34 UTC
**Describe the bug**
Methods check was disabled via /* sfge-disable-stack ApexFlsViolationRule */.
But InternalExecutionError error were thrown.

**To Reproduce**

Run the first scan.
sfdx scanner:run --format=csv --outfile=CodeAnalyzerGeneral.csv --target="./" --category="Security"

Run the second scan.
sfdx scanner:run:dfa --format=csv --outfile=CodeAnalyzerDFA.csv --target="./" --projectdir="./" --category="Security"

**Expected behavior**
After running the second scan csv file should be empty or with any errors described in documentation [link](https://forcedotcom.github.io/sfdx-scanner/en/v3.x/salesforce-graph-engine/introduction/)

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Scanner Version : @salesforce/sfdx-scanner 3.12.0

**Additional context**
**Stack trace:** 
Error and stacktrace: UnimplementedMethodException: ApexListValue:iterator, vertex=MethodCallExpressionVertex{fullMethodName=idStrings.iterator, referenceVertex=LazyVertex{result=ReferenceExpression{properties={FirstChild=true, Names=[idStrings], BeginLine=15, DefiningType_CaseSafe=utils, LastChild=true, DefiningType=Utils, EndLine=15, Name_CaseSafe=idstrings, childIdx=0, BeginColumn=37, ReferenceType=METHOD, Name=idStrings}}}, chainedNames=[idStrings], properties={FirstChild=true, FullMethodName=idStrings.iterator, BeginLine=15, FullMethodName_CaseSafe=idstrings.iterator, DefiningType_CaseSafe=utils, LastChild=false, DefiningType=Utils, EndLine=15, MethodName_CaseSafe=iterator, childIdx=0, BeginColumn=47, MethodName=iterator}}: com.salesforce.graph.symbols.apex.ApexListValue.apply(ApexListValue.java:310);com.salesforce.graph.symbols.PathScopeVisitor.handleApexValueMethod(PathScopeVisitor.java:1462);com.salesforce.graph.symbols.PathScopeVisitor.afterVisit(PathScopeVisitor.java:1222);com.salesforce.graph.symbols.DefaultSymbolProviderVertexVisitor.afterVisit(DefaultSymbolProviderVertexVisitor.java:749);com.salesforce.graph.vertex.MethodCallExpressionVertex.afterVisit(MethodCallExpressionVertex.java:79);com.salesforce.graph.ops.expander.ApexPathExpander.performAfterVisit(ApexPathExpander.java:577)

"Workaround": Have you found any ways to sidestep the problem?

"Urgency":"Business stopping"

**Comment by jfeingold35** [comment] 2023-09-18 14:57
@oldgunner , Can you please post a snippet of where you've added `/* sfge-disable-stack ApexFlsViolationRule */`, including the annotation and the method declaration?
(Also, does changing the annotation to simply `/* sfge-disable-stack */` resolve the error? `ApexFlsViolationRule` is no longer the only "Security" rule, so you may want the directive to disable rules more broadly instead of just that one specific rule.)

**Comment by oldgunner** [comment] 2023-09-18 19:02
@jfeingold35 
**Can you please post a snippet of where you've added /* sfge-disable-stack ApexFlsViolationRule */, including the annotation and the method declaration?**
```
@AuraEnabled
    /* sfge-disable-stack ApexFlsViolationRule */
    public static String saveDefaultOptions(List<String> optionValues, String optionType) {
```

**(Also, does changing the annotation to simply /* sfge-disable-stack */ resolve the error?**
I tried it, there was no success

Also I tried 
```
/* sfge-disable ApexFlsViolationRule */
public class MyClass {
```
error the same - Graph Engine identified your source and sink, but you must manually verify that you have a sanitizer in this path. Then, add an engine directive to skip the path. Next, create a Github issue for the Code Analyzer team that includes the error and stack trace. After we fix this issue, check the Code Analyzer release notes for more info. Error and stacktrace: UnimplementedMethodException: ApexListValue:iterator, vertex=MethodCallExpressionVertex{fullMethodName=idStrings.iterator, referenceVertex=LazyVertex{result=ReferenceExpression{properties={FirstChild=true, Names=[idStrings], BeginLine=15, DefiningType_CaseSafe=utils, LastChild=true, DefiningType=Utils, EndLine=15, Name_CaseSafe=idstrings, childIdx=0, BeginColumn=37, ReferenceType=METHOD, Name=idStrings}}}, chainedNames=[idStrings], properties={FirstChild=true, FullMethodName=idStrings.iterator, BeginLine=15, FullMethodName_CaseSafe=idstrings.iterator, DefiningType_CaseSafe=utils, LastChild=false, DefiningType=Utils, EndLine=15, MethodName_CaseSafe=iterator, childIdx=0, BeginColumn=47, MethodName=iterator}}: com.salesforce.graph.symbols.apex.ApexListValue.apply(ApexListValue.java:310);com.salesforce.graph.symbols.PathScopeVisitor.handleApexValueMethod(PathScopeVisitor.java:1462);com.salesforce.graph.symbols.PathScopeVisitor.afterVisit(PathScopeVisitor.java:1222);com.salesforce.graph.symbols.DefaultSymbolProviderVertexVisitor.afterVisit(DefaultSymbolProviderVertexVisitor.java:749);com.salesforce.graph.vertex.MethodCallExpressionVertex.afterVisit(MethodCallExpressionVertex.java:79);com.salesforce.graph.ops.expander.ApexPathExpander.performAfterVisit(ApexPathExpander.java:577)

Thanks!

**Comment by oldgunner** [comment] 2023-09-19 10:18
@jfeingold35 thanks for response!
on the 15th line of Utils.cls we parse converted to custom Iterable<String> either List<String> or Set<String>.
`
public static Set<Id> parseIds(Iterable<String> idStrings) {
        Set<Id> ids = new Set<Id>();

//the 15th line is below
        Iterator<String> iterator = idStrings.iterator();
        while(iterator.hasNext()) {
            String value = iterator.next();
            if (idPattern.matcher(value).matches()) {
                ids.add(Id.valueOf(value));
            }
        }

        return ids;
    }`

**Comment by stephen-carter-at-sf** [comment] 2024-06-03 19:16
Marking this as a duplicate of https://github.com/forcedotcom/sfdx-scanner/issues/1497

**Closed by stephen-carter-at-sf** 2024-06-03 19:16 UTC
Labels: duplicate, SFGE
