### ISSUE TITLE
[BUG] InternalExecutionError even /* sfge-disable-stack */  were assigned

### ISSUE THREAD

**Issue by programmer522** [forcedotcom/sfdx-scanner#1387] opened 2024-03-11 11:58 UTC
Fill out this template to submit your Code Analyzer issue.

**Description:**
Methods check was disabled via /* sfge-disable-stack */.
But InternalExecutionError error were thrown.

**Steps To Reproduce:
**Run the first scan.
sfdx scanner:run --format=csv --outfile=CodeAnalyzerGeneral.csv --target="./" --category="Security"

Run the second scan.
sfdx scanner:run:dfa --format=csv --outfile=CodeAnalyzerDFA.csv --target="./" --projectdir="./" --category="Security"

**Expected Behavior:**
After running the second scan csv file should be empty or with any errors described in documentation 

**Screenshots:**
None

**Desktop:**
<!--
Provide these details:
- Operating System. macOS Catalina
- Code Analyzer version. 3.21.0
- Salesforce CLI version.@salesforce/cli/2.30.8

**Additional Context:**
Graph Engine identified your source and sink, but you must manually verify that you have a sanitizer in this path. Then, add an engine directive to skip the path. Next, create a Github issue for the Code Analyzer team that includes the error and stack trace. After we fix this issue, check the Code Analyzer release notes for more info. Error and stacktrace: NumberFormatException: For input string: "": java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67);java.base/java.lang.Integer.parseInt(Integer.java:678);java.base/java.lang.Integer.valueOf(Integer.java:999);com.salesforce.graph.symbols.apex.ApexSimpleValueFactory.valueOf(ApexSimpleValueFactory.java:93);com.salesforce.graph.symbols.apex.ApexSimpleValueFactory.lambda$static$0(ApexSimpleValueFactory.java:22);com.salesforce.graph.ops.ApexStandardLibraryUtil.getStandardType(ApexStandardLibraryUtil.java:155)

**Workaround:**
Have you found any ways to sidestep the problem?

**Urgency:**
Businees stopping,, need to submit package for security review.

**Comment by jag-j** [comment] 2024-03-13 17:45
@programmer522 - Can you please give us the whole exception (along with your code snippets where this exception was thrown)? Thank you!

**Comment by programmer522** [comment] 2024-03-14 15:38
Exception: Graph Engine identified your source and sink, but you must manually verify that you have a sanitizer in this path. Then, add an engine directive to skip the path. Next, create a Github issue for the Code Analyzer team that includes the error and stack trace. After we fix this issue, check the Code Analyzer release notes for more info. Error and stacktrace: NumberFormatException: For input string: "": java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67);java.base/java.lang.Integer.parseInt(Integer.java:678);java.base/java.lang.Integer.valueOf(Integer.java:999);com.salesforce.graph.symbols.apex.ApexSimpleValueFactory.valueOf(ApexSimpleValueFactory.java:93);com.salesforce.graph.symbols.apex.ApexSimpleValueFactory.lambda$static$0(ApexSimpleValueFactory.java:22);com.salesforce.graph.ops.ApexStandardLibraryUtil.getStandardType(ApexStandardLibraryUtil.java:155)

Code:@AuraEnabled
/* sfge-disable-stack */
public static void updatesubmission(String[] conIDs,ID jobId)
{
String timeInter='';
list<TimeIntervalbtwTwoEmails__mdt> tirec=[select MasterLabel,DeveloperName from TimeIntervalbtwTwoEmails__mdt where Active__c = TRUE WITH SECURITY_ENFORCED];
if(!tirec.isEmpty())
{
for(TimeIntervalbtwTwoEmails__mdt tit:tirec)
{
timeInter=tit.MasterLabel;
}
}
if(tirec.isEmpty())
{
timeInter='1';
}
list<Submission__c> subrecNotif=[select Id,ApplicantNameByAccount__c,ApplicantNameByContact__c,ApplicantObject__c,JobAlertNotifiedDate__c,JobAlertSent__c from Submission__c where (ApplicantNameByAccount__c IN :conIDs OR ApplicantNameByContact__c In :conIDs) AND JobCode__c =:jobId WITH SECURITY_ENFORCED];
for(Submission__c subfor:subrecNotif)
{
if(subfor.JobAlertNotifiedDate__c == null && subfor.JobAlertSent__c == null)
{
subfor.JobAlertNotifiedDate__c=System.today();
subfor.JobAlertSent__c = 1;
}
else if(subfor.JobAlertNotifiedDate__c <= Date.today().addDays(-Integer.valueOf(timeInter)))
{
subfor.JobAlertNotifiedDate__c=System.today();
subfor.JobAlertSent__c = subfor.JobAlertSent__c + 1;

}
else if(subfor.JobAlertNotifiedDate__c ==System.today())
{
}
}
SObjectAccessDecision securityDecision = Security.stripInaccessible( AccessType.UPDATABLE, subrecNotif);
update securityDecision.getRecords();
}

**Comment by stephen-carter-at-sf** [comment] 2024-06-03 18:54
Marking this as a duplicate of https://github.com/forcedotcom/sfdx-scanner/issues/1497

**Closed by stephen-carter-at-sf** 2024-06-03 18:54 UTC
Labels: duplicate, SFGE
