### ISSUE TITLE
[BUG] Wrong Apex SOQL Injection Error & 

### ISSUE THREAD

**Issue by HeartlyHarsh** [forcedotcom/sfdx-scanner#1200] opened 2023-09-29 11:56 UTC
In my Apex Class, I am receiving a recordId as String in method. Using that recordId, I am doing dynamic SOQL query using Database.query.(query) method.

For prevent ApexSOQLInjection I have used Strip.escapeSingleQuotes(recordId) method while creating string for the Database query.

While scanning the code using code analyzer for first run, I am still getting related to ApexSOQLInjection. Which shows Rule -> "ApexSOQLInjectio"n & Description -> "Avoid untrusted/unescaped variables in DML query" 

I have below code.

databaseQuery = 'SELECT ' + currentRecordFields + ' FROM ' + objectApiName + ' WHERE Id = \'' + String.escapeSingleQuotes(recordId) + '\'';
currentSObjectRecordList = Database.query(databaseQuery);

While scanning my Apex Code for the Second run, It shows error as below, While my method start scanning.
Rule - > InternalExecutionError
Category -> InternalExecutionError
Description -> Graph Engine identified your source and sink, but you must manually verify that you have a sanitizer in this path. Then, add an engine directive to skip the path. Next, create a Github issue for the Code Analyzer team that includes the error and stack trace. After we fix this issue, check the Code Analyzer release notes for more info. Error and stacktrace: ClassCastException: class com.salesforce.graph.vertex.VariableExpressionVertex$Single cannot be cast to class com.salesforce.graph.vertex.SoqlExpressionVertex (com.salesforce.graph.vertex.VariableExpressionVertex$Single and com.salesforce.graph.vertex.SoqlExpressionVertex are in unnamed module of loader 'app'): com.salesforce.graph.symbols.apex.system.SObjectAccessDecision.buildSanitizedValue(SObjectAccessDecision.java:171);com.salesforce.graph.symbols.apex.system.SObjectAccessDecision.executeMethod(SObjectAccessDecision.java:112);com.salesforce.graph.symbols.PathScopeVisitor.afterMethodCall(PathScopeVisitor.java:659);com.salesforce.graph.symbols.DefaultSymbolProviderVertexVisitor.afterMethodCall(DefaultSymbolProviderVertexVisitor.java:318);com.salesforce.graph.ops.expander.ApexPathExpander.handleMethodCall(ApexPathExpander.java:681);com.salesforce.graph.ops.expander.ApexPathExpander.visit(ApexPathExpander.java:532)

Is there any issue with my code or with Code Analyzer. Do let me know if there is any other way to scan my code?

**Comment by HeartlyHarsh** [comment] 2023-09-29 15:02
currentSObjectRecordList is a List of Sobject, I inialized it as below.
List<SObject> currentSObjectRecordList = new List<SObject>();

currentRecordFields is a String, I have defined my code, where I have some logic and I am creating comma separated String of field's api name for soql query. 

objectApiName is String, I am receiving from LWC component. Its an object's api name.

recordId, I am getting from LWC from lighting record page where I have placed my component.

**Comment by jfeingold35** [comment] 2023-09-29 15:10
@HeartlyHarsh , I'm still unable to reproduce this on my end. Is it possible for you to provide a complete code block that reproduces the error?

**Comment by HeartlyHarsh** [comment] 2023-09-30 12:46
Hi, 
Regret for delay response.

I have attached here code & the csv file which were generated post Code Scan using code ananlyzer.

[CodeAnalyzerGeneral.csv](https://github.com/forcedotcom/sfdx-scanner/files/12774686/CodeAnalyzerGeneral.csv)
[DynamicController.txt](https://github.com/forcedotcom/sfdx-scanner/files/12774688/DynamicController.txt)

**Comment by jfeingold35** [comment] 2023-10-02 21:34
@HeartlyHarsh , I'm unable to reproduce with this file alone. Have you verified that scanning this file is enough to cause the error on your end?

**Comment by stephen-carter-at-sf** [comment] 2024-05-23 16:43
@HeartlyHarsh Can you check to see if you can reproduce this issue with our latest salesforce code analyzer v4 "latest-beta"? Do an
sf plugins install @salesforce/sfdx-scanner@latest-beta
to get the latest.

**Comment by stephen-carter-at-sf** [comment] 2024-05-23 16:55
@HeartlyHarsh 

If this is referring to PMD, then I am able to get

      {
        "line": 45,
        "column": 67,
        "endLine": 45,
        "endColumn": 80,
        "severity": 3,
        "ruleName": "ApexSOQLInjection",
        "category": "Security",
        "url": "https://docs.pmd-code.org/pmd-doc-7.0.0/pmd_rules_apex_security.html#apexsoqlinjection",
        "message": "\nAvoid untrusted/unescaped variables in DML query\n"
      }
      
If this is the issue you are referring to, then this is coming directly from PMD and not Salesforce Code Analyzer. In that case, can you please report this issue over in PMD's repo: https://github.com/pmd/pmd/issues  and then close this issue?

**Comment by stephen-carter-at-sf** [comment] 2024-05-31 13:06
Closing this issue due to lack of response. Feel free to reopen this issue if needed.

**Closed by stephen-carter-at-sf** 2024-05-31 13:06 UTC
Labels: BUG P3, Bug - Need more info
