### ISSUE TITLE
AccessLevel.USER_MODE causing InternalExectutionError

### ISSUE THREAD

**Issue by pesusich** [forcedotcom/sfdx-scanner#1140] opened 2023-08-01 23:30 UTC
**Describe the bug**
sfge does not recognize the overload for database.query(string, AccessLevel.USER_MODE)

```csv
"Problem","Severity","Source File","Source Line","Source Column","Source Type","Source Method","Sink File","Sink Line","Sink Column","Rule","Description","URL","Category","Engine"
"1","3","/Users/jordanpesusich/sfgeIssues/force-app/main/default/classes/genericController.cls","4","26","genericController","entryPoint1","","","","InternalExecutionError","Graph Engine identified your source and sink, but you must manually verify that you have a sanitizer in this path. Then, add an engine directive to skip the path. Next, create a Github issue for the Code Analyzer team that includes the error and stack trace. After we fix this issue, check the Code Analyzer release notes for more info. Error and stacktrace: UnexpectedException: MethodCallExpressionVertex{fullMethodName=database.query, referenceVertex=LazyVertex{result=ReferenceExpression{properties={FirstChild=true, Names=[database], BeginLine=8, DefiningType_CaseSafe=dataservice, LastChild=false, DefiningType=DataService, EndLine=8, Name_CaseSafe=database, childIdx=0, BeginColumn=22, ReferenceType=METHOD, Name=database}}}, chainedNames=[database], properties={FirstChild=true, FullMethodName=database.query, BeginLine=8, FullMethodName_CaseSafe=database.query, DefiningType_CaseSafe=dataservice, LastChild=false, DefiningType=DataService, EndLine=8, MethodName_CaseSafe=query, childIdx=0, BeginColumn=31, MethodName=query}}: com.salesforce.graph.symbols.apex.ApexSoqlValueFactory.lambda$static$0(ApexSoqlValueFactory.java:21);com.salesforce.graph.ops.ApexStandardLibraryUtil.getStandardType(ApexStandardLibraryUtil.java:154);com.salesforce.graph.symbols.PathScopeVisitor.afterVisit(PathScopeVisitor.java:1224);com.salesforce.graph.symbols.DefaultSymbolProviderVertexVisitor.afterVisit(DefaultSymbolProviderVertexVisitor.java:792);com.salesforce.graph.vertex.MethodCallExpressionVertex.afterVisit(MethodCallExpressionVertex.java:79);com.salesforce.graph.ops.expander.ApexPathExpander.performAfterVisit(ApexPathExpander.java:577)","https://forcedotcom.github.io/sfdx-scanner/en/v3.x/salesforce-graph-engine/rules/#ApexFlsViolationRule","InternalExecutionError","sfge"
```

**To Reproduce**
Simply 2 classes
```java
public with sharing class genericController {

    @AuraEnabled
    public static string entryPoint1(){
        try {
            DataService ds = new DataService();
            return ds.fetchUsers();
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}
```
```java
public with sharing class DataService {
    public DataService() {

    }
    public string fetchUsers(){
        string demoGarbage = '';
        string soql = 'SELECT Id FROM User';
        for(User u : database.query(soql,AccessLevel.USER_MODE)){
            demoGarbage += String.valueOf(u.Id);
        }
        return demoGarbage;
    }
}
```

**Expected behavior**

Clean result as FLS is respected

**Screenshots**
N/A

**Desktop (please complete the following information):**

 - OS: OSX
 - Scanner Version : 3.15

**Additional context**

"Workaround": Have you found any ways to sidestep the problem?

No - because of the exception being thrown - I am unable to successfully insert Engine directives to skip any code.

"Urgency": How severe is this problem? 

Unable to submit clean security review to submit my app

**Comment by jfeingold35** [comment] 2023-08-02 02:52
This seems to be a duplicate of #1122.

**Closed by jfeingold35** 2023-08-02 02:52 UTC
