### ISSUE TITLE
InternalExecutionError

### ISSUE THREAD

**Issue by udayvadagamdhruv** [forcedotcom/sfdx-scanner#1686] opened 2024-12-02 07:27 UTC
Graph Engine identified your source and sink, but you must manually verify that you have a sanitizer in this path. Then, add an engine directive to skip the path. Next, create a Github issue for the Code Analyzer team that includes the error and stack trace. After we fix this issue, check the Code Analyzer release notes for more info. Error and stacktrace: TodoException: What should I do if ApexValue from StandardCondition is not an ApexBooleanValue, ApexCustomValue, ApexForLoopValue, or ApexSingleValue: ApexValue=ApexValue(ApexSoqlValue) {status=INITIALIZED, declarationVertex=null, valueVertex=SoqlExpression{properties={FirstChild=true, BeginLine=1928, DefiningType_CaseSafe=approvaljobtaskext, LastChild=false, Query=[select id,name,Schedule_Roles__c,Email__c from Approval_Job_Task__c where id=:Taskid WITH SECURITY_ENFORCED], DefiningType=ApprovalJobTaskExt, EndLine=1928, childIdx=0, BeginColumn=46}}, resolvedValues={}, returnedFrom=null, invocableExpression=null, method=null}, parent=Unknown{conditionType=UNKNOWN, properties={FirstChild=true, BeginLine=1937, DefiningType_CaseSafe=approvaljobtaskext, LastChild=false, DefiningType=ApprovalJobTaskExt, EndLine=1937, childIdx=0, BeginColumn=48}}, vertex=MethodCallExpressionVertex{fullMethodName=Jtask.Schedule_Roles__c.contains, referenceVertex=LazyVertex{result=ReferenceExpression{properties={FirstChild=true, Names=[Jtask, Schedule_Roles__c], BeginLine=1937, DefiningType_CaseSafe=approvaljobtaskext, LastChild=false, DefiningType=ApprovalJobTaskExt, EndLine=1937, Name_CaseSafe=jtask.schedule_roles__c, childIdx=0, BeginColumn=24, ReferenceType=METHOD, Name=Jtask.Schedule_Roles__c}}}, chainedNames=[Jtask, Schedule_Roles__c], properties={FirstChild=true, FullMethodName=Jtask.Schedule_Roles__c.contains, BeginLine=1937, FullMethodName_CaseSafe=jtask.schedule_roles__c.contains, DefiningType_CaseSafe=approvaljobtaskext, LastChild=true, DefiningType=ApprovalJobTaskExt, EndLine=1937, MethodName_CaseSafe=contains, childIdx=0, BeginColumn=48, MethodName=contains}}: com.salesforce.rules.fls.apex.operations.SchemaBasedValidationAnalyzer.getDerivedApexValue(SchemaBasedValidationAnalyzer.java:89);com.salesforce.rules.fls.apex.operations.SchemaBasedValidationAnalyzer.getDerivedApexValue(SchemaBasedValidationAnalyzer.java:117);com.salesforce.rules.fls.apex.operations.SchemaBasedValidationAnalyzer.checkForValidation(SchemaBasedValidationAnalyzer.java:74);com.salesforce.rules.fls.apex.operations.FlsValidationCentral.checkSchemaBasedFlsValidation(FlsValidationCentral.java:71);com.salesforce.rules.fls.apex.AbstractFlsVisitor.afterVisit(AbstractFlsVisitor.java:80);com.salesforce.graph.vertex.StandardConditionVertex$Positive.afterVisit(StandardConditionVertex.java:108)

**Comment by stephen-carter-at-sf** [comment] 2024-12-02 13:10
Duplicate of https://github.com/forcedotcom/sfdx-scanner/issues/1497

**Closed** 2024-12-02 13:10 UTC
