### ISSUE TITLE
[BUG] Graph scan throws Internal Exception in output and log when scanning a method that contains `Describe Tabs` code

### ISSUE THREAD

**Issue by vc4u** [forcedotcom/sfdx-scanner#1191] opened 2023-09-21 20:57 UTC
**Describe the bug**
DFA scan generated output report and log files are showing an internal exception.

**Error:**
> 2023-09-22 02:18:35  ERROR ThreadableRuleExecutor:208 - Internal Error executing rule. submission=RuleRunnerSubmission{pathEntry=Method{properties={FirstChild=false, BeginLine=106, DefiningType_CaseSafe=util, LastChild=false, DefiningType=util, Constructor=false, EndLine=106, Name_CaseSafe=geticonname, childIdx=17, ReturnType=String, Name=getIconName, Arity=1, ReturnType_CaseSafe=string, BeginColumn=26}}, rules=[com.salesforce.rules.ApexFlsViolationRule@49b5d1e7, com.salesforce.rules.UseWithSharingOnDatabaseOperation@42442b03]}
com.salesforce.exception.UnexpectedException: ApexStandardValue{apexType='System.Schema'} ApexValue(SystemSchema) {status=INITIALIZED, declarationVertex=null, valueVertex=null, resolvedValues={}, returnedFrom=null, invocableExpression=null, method=null}
	at com.salesforce.graph.symbols.apex.system.SystemSchema.executeMethod(SystemSchema.java:106) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.symbols.PathScopeVisitor.afterMethodCall(PathScopeVisitor.java:659) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.symbols.DefaultSymbolProviderVertexVisitor.afterMethodCall(DefaultSymbolProviderVertexVisitor.java:318) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.expander.ApexPathExpander.handleMethodCall(ApexPathExpander.java:681) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.expander.ApexPathExpander.visit(ApexPathExpander.java:532) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.expander.ApexPathExpander.visit(ApexPathExpander.java:523) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.expander.ApexPathExpander.visit(ApexPathExpander.java:523) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.expander.ApexPathExpander.visit(ApexPathExpander.java:452) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.expander.ApexPathExpander.handleMethodCall(ApexPathExpander.java:676) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.expander.ApexPathExpander.visit(ApexPathExpander.java:532) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.expander.ApexPathExpander.visit(ApexPathExpander.java:523) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.expander.ApexPathExpander.visit(ApexPathExpander.java:452) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.expander.ApexPathExpanderUtil$ApexPathExpansionHandler.expand(ApexPathExpanderUtil.java:223) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.expander.ApexPathExpanderUtil$ApexPathExpansionHandler.expand(ApexPathExpanderUtil.java:162) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.expander.ApexPathExpanderUtil$ApexPathExpansionHandler._expand(ApexPathExpanderUtil.java:96) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.expander.ApexPathExpanderUtil$ApexPathExpansionHandler.access$100(ApexPathExpanderUtil.java:70) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.expander.ApexPathExpanderUtil.expand(ApexPathExpanderUtil.java:55) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.ApexPathUtil.getPaths(ApexPathUtil.java:201) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.ApexPathUtil.summarizeForwardPaths(ApexPathUtil.java:80) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.rules.PathBasedRuleRunner.getPathSummary(PathBasedRuleRunner.java:222) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.rules.PathBasedRuleRunner.runRules(PathBasedRuleRunner.java:75) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.rules.ThreadableRuleExecutor$CallableExecutor.runRules(ThreadableRuleExecutor.java:230) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.rules.ThreadableRuleExecutor$CallableExecutor.call(ThreadableRuleExecutor.java:167) [sfge-1.0.1-pilot.jar:?]
	at com.salesforce.rules.ThreadableRuleExecutor$CallableExecutor.call(ThreadableRuleExecutor.java:127) [sfge-1.0.1-pilot.jar:?]
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686) [?:?]
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.run(ForkJoinTask.java:1436) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
2023-09-22 02:18:35  INFO  ThreadableRuleExecutor:216 - Finished. method=util:getIconName:106

**Method:**
```
global static String getIconName(String sObjectName, boolean returnDefaultIfNone) {
	String u;
	List<Schema.DescribeTabSetResult> tabSetDesc    = Schema.describeTabs();
	List<Schema.DescribeTabResult> tabDesc          = new List<Schema.DescribeTabResult>();
	List<Schema.DescribeIconResult> iconDesc        = new List<Schema.DescribeIconResult>();

	for(Schema.DescribeTabSetResult tsr : tabSetDesc) { tabDesc.addAll(tsr.getTabs()); }

	for(Schema.DescribeTabResult tr : tabDesc) {
		if( sObjectName == tr.getSobjectName() ) {
			if( tr.isCustom() == true ) {
				iconDesc.addAll(tr.getIcons());
			} else {
				u = 'standard:' + sObjectName.toLowerCase();
			}
		}
	}
	for (Schema.DescribeIconResult ir : iconDesc) {
		if (ir.getContentType() == 'image/svg+xml'){
			u = 'custom:' + ir.getUrl().substringBetween('custom/','.svg').substringBefore('_');
			break;
		}
	}
	if (string.isBlank(u) && returnDefaultIfNone == true) {
		u = 'standard:custom';
	}
	return u;
}
```

**To Reproduce**

Execute following command for the method provided above:
`sf scanner run dfa -f html -o CodeAnalyzerDFA.html -p ./force-app/main/default -t ./force-app/main/default/classes/util.cls#getIconName --category "Security" --rule-thread-count 10 --sfgejvmargs "-Xmx4g" --pathexplimit "-1" --rule-thread-timeout 90000`

**Expected behavior**
Error should not be thrown, there is NO FLS or CRUD violation in provided method.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Scanner Version: v3.16.0

"Workaround": 
No

"Urgency": 
"Business stopping" as unable to scan project due to multiple errors thrown on similar lines all over the code base.

**Comment by vc4u** [comment] 2023-09-22 21:08
Is there any workaround to this? Or is there a way we can suppress scanning for this method?

Since no Error code being generated for this, I don't know how to suppress scanning of this - our scanner logs are bombarded with this and almost all other classes are reporting either timeout or Internal Server Error like this:
>Graph Engine identified your source and sink, but you must manually verify that you have a sanitizer in this path. Then, add an engine directive to skip the path. Next, create a Github issue for the Code Analyzer team that includes the error and stack trace. After we fix this issue, check the Code Analyzer release notes for more info. Error and stacktrace: UnexpectedException: ApexStandardValue{apexType='System.Schema'} ApexValue(SystemSchema) {status=INITIALIZED, declarationVertex=null, valueVertex=null, resolvedValues={}, returnedFrom=null, invocableExpression=null, method=null}: com.salesforce.graph.symbols.apex.system.SystemSchema.executeMethod(SystemSchema.java:106);com.salesforce.graph.symbols.PathScopeVisitor.afterMethodCall(PathScopeVisitor.java:659);com.salesforce.graph.symbols.DefaultSymbolProviderVertexVisitor.afterMethodCall(DefaultSymbolProviderVertexVisitor.java:318);com.salesforce.graph.ops.expander.ApexPathExpander.handleMethodCall(ApexPathExpander.java:681);com.salesforce.graph.ops.expander.ApexPathExpander.visit(ApexPathExpander.java:532);com.salesforce.graph.ops.expander.ApexPathExpander.visit(ApexPathExpander.java:523)

**Comment by jfeingold35** [comment] 2023-09-22 21:18
@vc4u , I understand your frustration, but unfortunately I don't think there's a workaround for this. We've added it to our backlog, and we can assess the level of effort that would be involved in a fix. We appreciate your patience in the meantime.

**Comment by stephen-carter-at-sf** [comment] 2024-06-03 19:15
Marking this as a duplicate of https://github.com/forcedotcom/sfdx-scanner/issues/1497

**Closed by stephen-carter-at-sf** 2024-06-03 19:15 UTC
Labels: duplicate, BUG P2, SFGE
