### ISSUE TITLE
[BUG] InternalExecutionError - UnimplementedMethodException: ApexStringValue:getSalesforceBaseUrl

### ISSUE THREAD

**Issue by az-oolloow** [forcedotcom/sfdx-scanner#1044] opened 2023-04-04 01:39 UTC
Running DFA in plugin 3.10.0 the code that looks like so:

```
String url = URL.getSalesforceBaseUrl().toExternalForm();
```

Throws an exception:

```
Graph Engine identified your source and sink, but you must manually verify that you have a sanitizer in this path. Then, add an engine directive to skip the path. Next, create a Github issue for the Code Analyzer team that includes the error and stack trace. After we fix this issue, check the Code Analyzer release notes for more info. Error and stacktrace: UnimplementedMethodException: ApexStringValue:getSalesforceBaseUrl, vertex=MethodCallExpressionVertex{fullMethodName=URL.getSalesforceBaseUrl, referenceVertex=LazyVertex{result=ReferenceExpression{properties={FirstChild=true, Names=[URL], BeginLine=575, DefiningType_CaseSafe=photogallerycontroller, LastChild=true, DefiningType=PhotoGalleryController, EndLine=575, Name_CaseSafe=url, childIdx=0, BeginColumn=22, ReferenceType=METHOD, Name=URL}}}, chainedNames=[URL], properties={FirstChild=true, FullMethodName=URL.getSalesforceBaseUrl, BeginLine=575, FullMethodName_CaseSafe=url.getsalesforcebaseurl, DefiningType_CaseSafe=photogallerycontroller, LastChild=true, DefiningType=PhotoGalleryController, EndLine=575, MethodName_CaseSafe=getsalesforcebaseurl, childIdx=0, BeginColumn=26, MethodName=getSalesforceBaseUrl}}: com.salesforce.graph.symbols.apex.ApexStringValue.apply(ApexStringValue.java:394);com.salesforce.graph.symbols.PathScopeVisitor.handleApexValueMethod(PathScopeVisitor.java:1462);com.salesforce.graph.symbols.PathScopeVisitor.afterVisit(PathScopeVisitor.java:1222);com.salesforce.graph.symbols.DefaultSymbolProviderVertexVisitor.afterVisit(DefaultSymbolProviderVertexVisitor.java:749);com.salesforce.graph.vertex.MethodCallExpressionVertex.afterVisit(MethodCallExpressionVertex.java:77);com.salesforce.graph.ops.expander.ApexPathExpander.visit(ApexPathExpander.java:721)
```

**Comment by stephen-carter-at-sf** [comment] 2024-06-03 19:05
Marking this as a duplicate of https://github.com/forcedotcom/sfdx-scanner/issues/1497

**Closed by stephen-carter-at-sf** 2024-06-03 19:05 UTC
Labels: duplicate, BUG P2, SFGE
