### ISSUE TITLE
[False Result] - $A' is not defined in Aura component & 'error' is defined but never use

### ISSUE THREAD

**Issue by GreeshmaVSTR** [forcedotcom/sfdx-scanner#1343] opened 2024-02-01 10:38 UTC
### Salesforce Code Analyzer False Results Template

**Description:**
The sfdx-scanner, in run mode, reports that the $A variable is not defined in the Javascript and throws an error of Severity 2. The $A entity is built into the Aura component framework, and so the Salesforce analyzer should recognize it as predefined.
Another error is no-unused-vars ('error' is defined but never use) with severity 2

**Rule                   Priority         Message**
no-undef                  2               '$A' is not defined.
no-unused-vars        2               'error' is defined but never use

**Comment by johnbelosf** [comment] 2024-02-01 11:03
Duplicate of #1331

**Closed by johnbelosf** 2024-02-01 11:03 UTC
