### ISSUE TITLE
InternalExecutionError on Standard Salesforce methods

### ISSUE THREAD

**Issue by sgokhru** [forcedotcom/sfdx-scanner#1559] opened 2024-07-30 19:32 UTC
UUID.randomUUID method is causing UnimplementedMethodException

Graph Engine identified your source and sink, but you must manually verify that you have a sanitizer in this path. Then, add an engine directive to skip the path. Next, create a Github issue for the Code Analyzer team that includes the error and stack trace. After we fix this issue, check the Code Analyzer release notes for more info. Error and stacktrace: UnimplementedMethodException: ApexStringValue:randomUUID, vertex=MethodCallExpressionVertex{fullMethodName=UUID.randomUUID, referenceVertex=LazyVertex{result=ReferenceExpression{properties={FirstChild=true, Names=[UUID], BeginLine=109, DefiningType_CaseSafe=sessioncontroller, LastChild=true, DefiningType=SessionController, EndLine=109, Name_CaseSafe=uuid, childIdx=0, BeginColumn=23, ReferenceType=METHOD, Name=UUID}}}, chainedNames=[UUID], properties={FirstChild=true, FullMethodName=UUID.randomUUID, BeginLine=109, FullMethodName_CaseSafe=uuid.randomuuid, DefiningType_CaseSafe=sessioncontroller, LastChild=true, DefiningType=SessionController, EndLine=109, MethodName_CaseSafe=randomuuid, childIdx=0, BeginColumn=28, MethodName=randomUUID}}: com.salesforce.graph.symbols.apex.ApexStringValue.apply(ApexStringValue.java:708);com.salesforce.graph.symbols.PathScopeVisitor.handleApexValueMethod(PathScopeVisitor.java:1487);com.salesforce.graph.symbols.PathScopeVisitor.afterVisit(PathScopeVisitor.java:1242);com.salesforce.graph.symbols.DefaultSymbolProviderVertexVisitor.afterVisit(DefaultSymbolProviderVertexVisitor.java:800);com.salesforce.graph.vertex.MethodCallExpressionVertex.afterVisit(MethodCallExpressionVertex.java:79);com.salesforce.graph.ops.expander.ApexPathExpander.performAfterVisit(ApexPathExpander.java:577)

Please let me know how to fix this issue.

**Comment by jag-j** [comment] 2024-08-01 02:18
Hello @sgokhru, We suspect this is a known issue. Can you please paste the exact line of code where this error is thrown? Thank you!

**Comment by stephen-carter-at-sf** [comment] 2024-08-29 13:19
Duplicate of 1497

**Closed by stephen-carter-at-sf** 2024-08-29 13:19 UTC
Labels: Bug - Need more info, SFGE
