### ISSUE TITLE
[BUG] SFGE throws when root directory is specified as the --projectdir due to SFDX files

### ISSUE THREAD

**Issue by jamessimone** [forcedotcom/sfdx-scanner#1007] opened 2023-03-07 17:29 UTC
**Describe the bug**

Running:

```
sfdx scanner:run -e sfge -p . --target 'rollup,plugins,extra-tests,!plugins/ExtraCodeCoverage/**'
```

[In my repo](https://github.com/jamessimone/apex-rollup) leads to the following error being thrown:

```
ERROR: Salesforce Graph Engine encountered an error and couldn't complete analysis: Graph engine encountered compilation errors.
Fix the errors in ~\apex-rollup\node_modules\@salesforce\templates\lib\templates\apexclass\ApexException.cls and retry., 
Caused by:
Invalid syntax at 1:15. (Found punctuation symbol or operator '%' that isn't valid in Apex.)
Invalid syntax at 1:26. (Found punctuation symbol or operator '%' that isn't valid in Apex.)
Invalid syntax at 1:14. (Unexpected token '<'.)
Invalid syntax at 1:16. (Unexpected token '='.)
```

**To Reproduce**

Clone the repo and run the above command

**Expected behavior**

I personally wouldn't ever expect `node_modules` to be considered a valid directory to scan, but I'm open to other options like the ability to stipulate excluded directories.

**Desktop (please complete the following information):**
 - OS: Windows
 - Scanner Version 3.10.0

**Comment by rmohan20** [comment] 2023-03-10 17:40
@jamessimone Thanks for letting us know. This is certainly a bug - we'll prioritize this.

In the meantime, as a workaround, in `<home>/.sfdx-scanner/Config.json`, can you add exclusion for `node_modules` in sfge's target pattern config:

```
       {
            "name": "sfge",
            "targetPatterns": [
                "**/*.cls",
                "**/*.trigger",
                "!**/node_modules/**",
            ],
            "disabled": false
        }
```

**Comment by jamessimone** [comment] 2023-03-10 20:24
@rmohan20 thanks! Interestingly, even with that in my `targetPatterns` object, the command finishes but I still get this printed to my console:

```
$ sfdx scanner:run -e sfge -p . --target 'rollup,plugins,extra-tests,!plugins/ExtraCodeCoverage/**'
WARNING: We're continually improving Salesforce Code Analyzer. Tell us what you think! Give feedback at https://research.net/r/SalesforceCA
Analyzing with Salesforce Graph Engine. See ~\.sfdx-scanner\sfge.log for details.... Error
ERROR: Salesforce Graph Engine encountered an error and couldn't complete analysis: Graph engine encountered compilation errors. Fix the errors in ~\Code\rollup\node_modules\@salesforce\templates\lib\templates\apexclass\ApexException.cls and retry., Caused by:
Invalid syntax at 1:15. (Found punctuation symbol or operator '%' that isn't valid in Apex.)
Invalid syntax at 1:26. (Found punctuation symbol or operator '%' that isn't valid in Apex.)
Invalid syntax at 1:14. (Unexpected token '<'.)
Invalid syntax at 1:16. (Unexpected token '='.)
```

**Comment by rmohan20** [comment] 2023-03-10 23:26
@jamessimone Extremely weird. Thanks for trying out the steps. I suppose this is the first time we've come across `.cls` files in node_modules :)
Will post an update when we have more information.

**Comment by jfeingold35** [comment] 2023-09-13 18:18
@jamessimone , are you able to reproduce this issue on v3.16.0 of the analyzer? We suspect that the fix for #1160 may have also resolved this Issue, but we want to check with you.

**Comment by jamessimone** [comment] 2023-09-13 19:10
@jfeingold35 interesting - looks like progress has been made, but still getting false positives printed to the console prior to the `Executed engines: sfge. No rule violations found.`:

 `$ sfdx scanner:run -e sfge -p . --target 'rollup,plugins,extra-tests,!plugins/ExtraCodeCoverage/**'` outputs (with some minor cleanup by me in the way of meaningful line breaks):

```
Analyzing with Salesforce Graph Engine. See C:\Users\james.simone\.sfdx-scanner\sfge.log for details.... Error
ERROR: Salesforce Graph Engine encountered an error and couldn't complete analysis: Graph engine encountered compilation errors. 
Fix the errors in ~\Documents\Code\apex-rollup\.sfdx\tools\246\StandardApexLibrary\ApexPages\IdeaStandardController.cls and retry., 
Caused by: Invalid syntax at 4:30. (Unexpected token 'delete'.)

Executed engines: sfge. No rule violations found.
```

**Comment by jfeingold35** [comment] 2023-09-13 19:47
@jamessimone , stupid question, but are you sure you're on version 3.16.0? I'm able to reproduce this behavior on 3.15.0, but not 3.16.0.
What does `sfdx plugins` indicate?

**Comment by jamessimone** [comment] 2023-09-13 19:55
@jfeingold35 no such thing as a stupid question! You were right, it was 3.15.0 that was running (even though locally within this repository I had upgraded my npm dependency and had re-run `sfdx plugins:link ./node_modules/@salesforce/sfdx-scanner` - let me know if there's something there that seems amiss). On 3.16.0, I don't have this problem.

**Comment by jfeingold35** [comment] 2023-09-13 20:35
@jamessimone , not sure why that would have happened, but glad it's sorted now. I'm going to close this as a duplicate of #1160.
That said, the point about us not respecting files in `.gitignore` or `.forceignore` is a good one. I've created an item for it and added it to our backlog. Thanks for the suggestion!

**Closed by jfeingold35** 2023-09-13 20:35 UTC
Labels: BUG P1

**Comment by jamessimone** [comment] 2023-09-13 20:51
Thanks!
