### ISSUE TITLE
@W-7921470@ ESLINT report missing information

### ISSUE THREAD

**Issue by davidbrowaeys** [forcedotcom/sfdx-scanner#176] opened 2020-08-25 05:13 UTC
Hi there, 

if you run scanner for eslint it doesn't seem to include **rule name and category**

```
sfdx scanner:run --target ./**/lwc/**/*.js
```

**Sample JSON output:**
![image](https://user-images.githubusercontent.com/20630942/91125505-3a67c580-e6e5-11ea-93e2-93bc577885e8.png)

Is there something to add in order to make it work ?

**Comment by jbartolotta-sfdc** [comment] 2020-08-25 15:31
@davidbrowaeys - Thanks for the report. The output doesn't show the rule or category in this case because it is a Parsing error and not a Rule violation. 

The root cause is that the scanner is using the default eslint engine without the configuration required to scan advanced features such as decorators. Adding support for this use case is actively being developed and should be available in the next patch release. I will let you know when it is available.

More information on the particulars of scanning LWC with eslint can be found in the `Usage` section in the [eslint-plugin-lwc repo](https://github.com/salesforce/eslint-plugin-lwc)

**Comment by jbartolotta-sfdc** [comment] 2020-09-23 20:50
@davidbrowaeys we have just released version 2.2.0 that adds support for scanning LWC files. The following command will invoke the `eslint-lwc` engine and show you LWC specific errors.

```sfdx scanner:run --target './**/lwc/**/*.js' --engine eslint-lwc --category LWC```

Omitting `--category LWC` will show you all eslint and eslint-lwc violations at once. 

You can upgrade the plugin to 2.2.0 by invoking ```sfdx plugins:update```

A couple of things to note.

1. Scanning non-LWC Javascript with the eslint and eslint-lwc engines may return slightly different violations because they use different parsers. The parser used by the `eslint-lwc` engine is slightly more forgiving and doesn't throw as many parsing errors.
2. The eslint-lwc engine is disabled by default and will only run when specified via the `--engine` flag. We are still deciding on which engines will be enabled by default in the 3.x release.

Please let us know if you have any issues or questions.

**Comment by jbartolotta-sfdc** [comment] 2020-10-08 17:13
Closing, this has been fixed.

**Closed by jbartolotta-sfdc** 2020-10-08 17:13 UTC
