### ISSUE TITLE
[BUG] InternalExecutionError has been thrown when running sf scanner run dfa

### ISSUE THREAD

**Issue by Jellybean0708** [forcedotcom/sfdx-scanner#1589] opened 2024-08-22 10:15 UTC
### Have you tried to resolve this issue yourself first?

Yes

### Bug Description

An InternalExecutionError error has been thrown during run sf scanner dfa.
Here is code.
![image](https://github.com/user-attachments/assets/c0b33d91-f96e-4cd5-be9d-e41277e16163)

### Output / Logs

"6","3","D:\PMS e-cloudsoft\ec-print-gitee\eDocument DX-master\force-app\main\default\classes\ECP_DataMappingCtrl.cls","465","39","ECP_DataMappingCtrl","getApiRefMap","","","","InternalExecutionError","Graph Engine identified your source and sink, but you must manually verify that you have a sanitizer in this path. Then, add an engine directive to skip the path. Next, create a Github issue for the Code Analyzer team that includes the error and stack trace. After we fix this issue, check the Code Analyzer release notes for more info. Error and stacktrace: UnexpectedException: ArrayLoadExpression{properties={FirstChild=true, BeginLine=471, DefiningType_CaseSafe=ecp_datamappingctrl, LastChild=false, DefiningType=ECP_DataMappingCtrl, EndLine=471, childIdx=0, BeginColumn=48}}: com.salesforce.graph.symbols.PathScopeVisitor.afterVisit(PathScopeVisitor.java:761);com.salesforce.graph.symbols.DefaultSymbolProviderVertexVisitor.afterVisit(DefaultSymbolProviderVertexVisitor.java:737);com.salesforce.graph.vertex.ArrayLoadExpressionVertex.afterVisit(ArrayLoadExpressionVertex.java:58);com.salesforce.graph.ops.expander.ApexPathExpander.performAfterVisit(ApexPathExpander.java:577);com.salesforce.graph.ops.expander.ApexPathExpander.visit(ApexPathExpander.java:536);com.salesforce.graph.ops.expander.ApexPathExpander.visit(ApexPathExpander.java:523)","https://developer.salesforce.com/docs/platform/salesforce-code-analyzer/guide/apexflsviolation-rule.html","InternalExecutionError","sfge"

### Steps To Reproduce

Run the below command with sf scanner extension:
sfdx scanner run dfa --format csv --outfile CodeAnalyzerDFA.csv --target="./" --projectdir="./" --category="Security" --sfgejvmargs "-Xmx10g" --pathexplimit -1 --rule-thread-count 2 --rule-thread-timeout 3600000

### Expected Behavior

The result should show the code issue instead of the Internal Execution error.

### Operating System

Windows 11

### Salesforce CLI Version

@salesforce\cli\2.42.6 win32-x64 node-v20.12.2

### Code Analyzer Plugin (@salesforce/sfdx-scanner) Version

@salesforce/sfdx-scanner: 4.3.2

### Java Version

java version "17.0.9" 2023-10-17 LTS

### Urgency

Low

**Comment by stephen-carter-at-sf** [comment] 2024-08-23 17:23
Duplicate of 1497.

**Closed by stephen-carter-at-sf** 2024-08-23 17:23 UTC
