### ISSUE TITLE
[BUG] running dfa command

### ISSUE THREAD

**Issue by paavilio** [forcedotcom/sfdx-scanner#1249] opened 2023-11-23 14:48 UTC
Hi team,
When running the command sfdx scanner:run:dfa --target "./force-app/main/default/classes/bvi_CalloutCSQ.cls" --projectdir "./force-app/" I met the following error:

"ERROR running scanner:run:dfa:   nov 23, 2023 3:35:11 PM apex.jorje.parser.impl.BaseApexLexer dedupe"

Open VS Code
login to the SF org with sfdx
Execute the command "sfdx scanner:run:dfa --target "./force-app/main/default/classes/bvi_CalloutCSQ.cls" --projectdir "./force-app/"

Expected behavior
No errors since the apex class compiles and is deployed without error.

Desktop

OS:Windows 11
Scanner Version 3.17.0

`sfdx scanner:run:dfa --target "./force-app/main/default/classes/bvi_CalloutCSQ.cls" --projectdir "./force-app/"          
 »   Warning: @salesforce/cli update available from 2.15.9 to 2.17.14.
WARNING: We're continually improving Salesforce Code Analyzer. Tell us what you think! Give feedback at https://research.net/r/SalesforceCA
(node:11452) Warning: Deprecated config name: apiVersion. Please use org-api-version instead.
(Use `node --trace-warnings ...` to show where the warning was created)
Analyzing with Salesforce Graph Engine. See C:\Users\paolo\.sfdx-scanner\sfge.log for details.... Error
ERROR running scanner:run:dfa:   nov 23, 2023 3:35:11 PM apex.jorje.parser.impl.BaseApexLexer dedupe
INFORMAZIONI: Deduped array ApexLexer.DFA22_transition. Found 7075528 shorts which is 13MB not including array overhead. Removed 6418975 shorts which is 12MB not counting array overhead. Took 6 ms.
Unexpected exception while loading graph. See logs for more information.`

**Comment by jfeingold35** [comment] 2023-11-27 14:20
@paavilio , our latest version is 3.18. What happens when you try this against 3.18 instead of 3.17?

**Comment by jfeingold35** [comment] 2023-12-27 17:24
This appears to be a duplicate of #1234

**Closed by jfeingold35** 2023-12-27 17:24 UTC
