### ISSUE TITLE
[BUG] DML as user is throwing an error on scan

### ISSUE THREAD

**Issue by jaelee125** [forcedotcom/sfdx-scanner#1120] opened 2023-07-19 22:21 UTC
**Describe the bug**
DML as user is thrown an error on scan

**To Reproduce**
In Apex, write any DML as user

**Expected behavior**
Code Scan should complete without any issues

**Screenshots**
Error Message: 
"Problem","Severity","File","Line","Column","Rule","Description","URL","Category","Engine"
"1","1","/Users/jae/code/specright2gp/nzcsustainability/main/default/classes/Rollup/JunctionRollupHandler.cls","1","1","files-must-compile","PMDException: Error while parsing /Users/jae/code/specright2gp/nzcsustainability/main/default/classes/Rollup/JunctionRollupHandler.cls
Caused by: net.sourceforge.pmd.lang.ast.ParseException: apex.jorje.services.exception.ParseException: Syntax(error = UnexpectedToken(loc = (99, 11, 699, 701), token = 'as'))","","Scanner Internal","pmd"

**Additional context**
Because this is a new feature, my guess is code scanner hasn't been updated

"Workaround": Have you found any ways to sidestep the problem?
I just commented out the problematic dml statement and ran the scanner again

"Urgency": How severe is this problem? "Business stopping" vs "Not business-stopping".
Non business-stopping since I can just comment out the one problematic dml statement I have in the package

**Comment by jfeingold35** [comment] 2023-07-19 22:25
This is a duplicate of #1091 . Please see the comments on that Issue for an explanation of the problem.
Thanks!

**Closed by jfeingold35** 2023-07-19 22:25 UTC
Labels: duplicate
