### ISSUE TITLE
[BUG] apex.jorje.parser.impl.BaseApexLexer dedupe

### ISSUE THREAD

**Issue by jaelee125** [forcedotcom/sfdx-scanner#1234] opened 2023-11-01 17:21 UTC
When I run the scan with the following parameters:
sfdx scanner:run:dfa -f=csv -o=CodeAnalyzerDFA.csv -t="./" -p="./" --normalize-severity --sfgejvmargs "-Xmx150g" --pathexplimit -1 --rule-thread-count 2 --rule-thread-timeout 99000000
I get this error:
ERROR: Salesforce Graph Engine encountered an error and couldn't complete analysis: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError, Caused by:
java.lang.OutOfMemoryError

However, if I increase the memory to 200g, I keep getting this error:
apex.jorje.parser.impl.BaseApexLexer dedupe
INFO: Deduped array ApexLexer.DFA22_transition. Found 7075528 shorts which is 13MB not including array overhead. Removed 6418975 shorts which is 12MB not counting array overhead. Took 11 ms.

**Comment by jaelee125** [comment] 2023-11-02 17:18
@jfeingold35 Can you help with this issue?

**Comment by jfeingold35** [comment] 2023-11-02 18:08
@jaelee125 , this sounds like an issue parsing a file. Have you checked `~/.sfdx-scanner/sfge.log` to see which file fails to parse? That information should be accessible in the log.

**Comment by jfeingold35** [comment] 2023-11-02 18:09
@jaelee125 , additionally, have you consulted the [troubleshooting steps](https://forcedotcom.github.io/sfdx-scanner/en/v3.x/troubleshooting/#issues-using-salesforce-graph-engine) yet?

**Comment by jaelee125** [comment] 2023-11-02 18:34
I'll take a look. Thank you

**Comment by rmohan20** [comment] 2024-03-13 06:47
Duplicate of #1294

**Comment by RenzR-BIP** [comment] 2024-03-22 09:30
Hi, while running the tool I encountered the error below.

Specifically I ran this command:
`sfdx scanner:run:dfa --target "./force-app/main/default/classes/class_name.cls" --projectdir "./force-app/"`

The error is:
`2024-03-22 10:19:56  ERROR Main:156 - Unexpected exception while loading graph
com.salesforce.exception.UnexpectedException: vertex=ArrayLoadExpression{DefiningType=bvi_CreateAndManageWOT_Controller, BeginLine=144, EndLine=144}, labels=[Ljava.lang.String;@1d1fd2aa
	at com.salesforce.graph.build.MethodPathBuilderVisitor.assertVertexLabel(MethodPathBuilderVisitor.java:638) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor.visitSwitchStatement(MethodPathBuilderVisitor.java:436) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor._visit(MethodPathBuilderVisitor.java:140) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor._visit(MethodPathBuilderVisitor.java:159) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor._visit(MethodPathBuilderVisitor.java:159) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor._visit(MethodPathBuilderVisitor.java:159) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor._visit(MethodPathBuilderVisitor.java:159) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor._visit(MethodPathBuilderVisitor.java:159) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor._visit(MethodPathBuilderVisitor.java:159) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor._visit(MethodPathBuilderVisitor.java:159) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor._visit(MethodPathBuilderVisitor.java:159) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor._visit(MethodPathBuilderVisitor.java:159) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.MethodPathBuilderVisitor.apply(MethodPathBuilderVisitor.java:97) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.AbstractApexVertexBuilder.afterInsert(AbstractApexVertexBuilder.java:169) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.AbstractApexVertexBuilder.buildVertices(AbstractApexVertexBuilder.java:153) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.AbstractApexVertexBuilder.buildVertices(AbstractApexVertexBuilder.java:125) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.AbstractApexVertexBuilder.buildVertices(AbstractApexVertexBuilder.java:35) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.CustomerApexVertexBuilder.build(CustomerApexVertexBuilder.java:21) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.build.Util.buildGraph(Util.java:39) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.graph.ops.GraphUtil.loadSourceFolders(GraphUtil.java:170) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.Main$Dependencies.loadSourceFoldersToGraph(Main.java:247) ~[sfge-1.0.1-pilot.jar:?]
	at com.salesforce.Main.execute(Main.java:150) [sfge-1.0.1-pilot.jar:?]
	at com.salesforce.Main.process(Main.java:100) [sfge-1.0.1-pilot.jar:?]
	at com.salesforce.Main.main(Main.java:68) [sfge-1.0.1-pilot.jar:?]`

Thanks in advance

**Comment by stephen-carter-at-sf** [comment] 2024-05-23 17:39
@jaelee125 Can you try seeing if our latest-beta version of code analyzer fixes this for you.

sf plugins install @salesforce/sfdx-scanner@latest-beta

**Comment by stephen-carter-at-sf** [comment] 2024-07-23 13:43
Received no reply back... closing this issue for now.

**Closed by stephen-carter-at-sf** 2024-07-23 13:43 UTC
Labels: BUG P3, Bug - Need more info
