### ISSUE TITLE
[BUG] InternalExecutionError while running -> sfdx scanner:run:dfa

### ISSUE THREAD

**Issue by Aron-Polner** [forcedotcom/sfdx-scanner#1212] opened 2023-10-04 09:23 UTC
**Describe the bug**
InternalExecutionError when running 
```
sfdx scanner:run:dfa --format=csv --outfile=CodeAnalyzerDFA.csv --target="./" --projectdir="./" --category="Security"
```

**To Reproduce**
Run the above command

**Expected behavior**
From my understanding of the issue the Grapher Engine, apart from throwing an `InternalExecutionError`, suspects that there might be an ApexFlsViolation related to the code on line 4 in `ContactFetcher.cls`. However, I can't silence the error by adding `/* sfge-disable-stack ApexFlsViolationRule */` on the line above the method. Neither can I silence the code analyzer by adding `/* sfge-disable-next-line ApexFlsViolationRule */` above the lines inside of the method. Which I find very strange. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.7.10
 - Scanner Version: @salesforce/cli/2.10.2 darwin-x64 node-v18.15.0

**Additional context**
```
"Problem","Severity","Source File","Source Line","Source Column","Source Type","Source Method","Sink File","Sink Line","Sink Column","Rule","Description","URL","Category","Engine"
"1","3","/xyz-not-important-for-context/ContactFetcher.cls","5","26","ContactFetcher","getManagedPackageVersion","","","","InternalExecutionError","Graph Engine identified your source and sink, but you must manually verify that you have a sanitizer in this path. Then, add an engine directive to skip the path. Next, create a Github issue for the Code Analyzer team that includes the error and stack trace. After we fix this issue, check the Code Analyzer release notes for more info. Error and stacktrace: UnexpectedException: Did not expect NOT_A_MATCH when ranking parameter match. parameterType = Version, type = OrderedTreeSet{internalList=[NULL, Object]}: com.salesforce.graph.ops.TypeableUtil.rankParameterMatch(TypeableUtil.java:211);com.salesforce.graph.vertex.Typeable.rankParameterMatch(Typeable.java:41);com.salesforce.graph.ops.MethodTypeMatchUtil.getMatchRank(MethodTypeMatchUtil.java:191);com.salesforce.graph.ops.MethodTypeMatchUtil.parameterTypesMatch(MethodTypeMatchUtil.java:128);com.salesforce.graph.ops.MethodUtil.getInvoked(MethodUtil.java:358);com.salesforce.graph.ops.MethodUtil.getInvoked(MethodUtil.java:158)","https://forcedotcom.github.io/sfdx-scanner/en/v3.x/salesforce-graph-engine/rules/#ApexFlsViolationRule","InternalExecutionError","sfge"
```

**Code that the analyzer is complaining about**

ContactFetcher.cls
_line 5 is at public static String..._
```
    @RemoteAction
    public static String getManagedPackageVersion() {
        Version version = PackageMetadata.getManagedPackageVersion();
        return getManagedPackageVersion(version);
    }

    @TestVisible
    private static String getManagedPackageVersion(System.Version version) {
        if (version == null) {
            return null;
        }

        String majorMinor = version.major() + '.' + version.minor();
        if (version.patch() != null) {
            majorMinor += '.' + version.patch();
        }
        return majorMinor;
    }
```

PackageMetadata.cls
```
  public with sharing class PackageMetadata {
      public static Version getManagedPackageVersion() {
          try {
              // Inspiration: https://salesforce.stackexchange.com/a/11050
              UserInfo.isCurrentUserLicensed('xyz');
              return System.requestVersion();
          } catch (TypeException e) {
              return null;
          }
      }
  }
```

"Workaround": N/A

"Urgency": "Business stopping". We need 0 violations to push new SF code into production.

**Comment by jfeingold35** [comment] 2023-10-04 13:53
@Aron-Polner , a few notes:
1. This is a duplicate of known issue #1195 .
2. If by "push new SF code into production", you're referring to the need to pass security review, then this is not a business stopper. False positives and errors can be documented as part of the security review process.

**Closed by jfeingold35** 2023-10-04 13:53 UTC

**Comment by Aron-Polner** [comment] 2023-10-04 13:59
Ok, changing the return type from Version to Object sorted the issue out if that is any help for your devs when they try to sort this out.
