### ISSUE TITLE
[BUG] Unexpected close tag Error

### ISSUE THREAD

**Issue by jiacheng-xu** [forcedotcom/sfdx-scanner#1499] opened 2024-06-06 23:28 UTC
### Have you tried to resolve this issue yourself first?

Yes

### Bug Description

This issue is raised by sfdx internally.

I am using PMD scanner to scan apex code and find violations. 

Error message I get:
```
Warning: We're continually improving Salesforce Code Analyzer. Tell us what you think! Give feedback at https://research.net/r/SalesforceCA
Error (1): Unexpected close tag
Line: 67360
Column: 8
Char: >
```

The command I run: `sfdx scanner:run -f json -o tmp_196f0ab2712d4a5fbd18b52b245c343e/pmd_output.json --pmdconfig artifacts/pmd_ruleset_enhanced.xml -t tmp_196f0ab2712d4a5fbd18b52b245c343e/`

I am not able to share the files under this folder externally. It contains 3000+ apex classes (in .cls). But it might not be apex code.

### Output / Logs

```
Warning: We're continually improving Salesforce Code Analyzer. Tell us what you think! Give feedback at https://research.net/r/SalesforceCA
Error (1): Unexpected close tag
Line: 67360
Column: 8
Char: >
```

### Steps To Reproduce

The command I run: `sfdx scanner:run -f json -o tmp_196f0ab2712d4a5fbd18b52b245c343e/pmd_output.json --pmdconfig artifacts/pmd_ruleset_enhanced.xml -t tmp_196f0ab2712d4a5fbd18b52b245c343e/`

### Expected Behavior

the violations will be saved in the target json.

### Operating System

NAME="Ubuntu" VERSION="20.04.6 LTS (Focal Fossa)" ID=ubuntu ID_LIKE=debian PRETTY_NAME="Ubuntu 20.04.6 LTS" VERSION_ID="20.04" HOME_URL="https://www.ubuntu.com/" SUPPORT_URL="https://help.ubuntu.com/" BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/" PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy" VERSION_CODENAME=focal UBUNTU_CODENAME=focal

### Salesforce CLI Version

@salesforce/cli/2.44.8 linux-x64 node-v20.14.0

### Code Analyzer Plugin (@salesforce/sfdx-scanner) Version

@salesforce/sfdx-scanner 4.2.0 (latest-beta)  Uninstalled JIT Plugins: community 3.2.14 custom-metadata 3.3.10 dev 2.3.1 devops-center 1.2.13 env 3.0.30 functions 1.23.0 signups 2.3.5 @salesforce/sfdx-plugin-lwc-test 1.2.0

### Additional Context (Screenshots, Files, etc)

Context: I am using scanner to scan up to hundred thousands of code files. I have successfully scanned a lot of code and I believe one of the file or the content of file caused this issue. 
MAX number of lines of each file is 10k.

### Urgency

Critical

**Comment by stephen-carter-at-sf** [comment] 2024-06-07 11:46
@jiacheng-xu Can you send me the full output and the log?

Does your artifacts/pmd_ruleset_enhanced.xml work on other files? Have you tried running PMD independent of Salesforce Code Analyzer to see if it is specific to one or the other?

**Comment by stephen-carter-at-sf** [comment] 2024-06-07 22:13
OK I have determined your problem. Thanks for reaching out to me and sharing your files.

The issue is that one of your files has CDATA and it isn't valid apex code. Then when PMD reads the file, it creates an error in its xml with your CDATA wrapped inside of their CDATA... but they fail to escape your CDATA. This is a PMD bug.

I filed this issue with them:
https://github.com/pmd/pmd/issues/5059

When they have fixed this issue on their end, then we'll upgrade the version of PMD that code analyzer users.

Until then, please remove CDATA from the files that you are scanning... or make the apex class files parsable by PMD first.

Closing this issue because it isn't associated with code analyzer directly - but instead is a bug with PMD.

**Closed by stephen-carter-at-sf** 2024-06-07 22:13 UTC
Labels: Bug - Need more info
