### ISSUE TITLE
Null Coalescing Operator (??) causing issues on Code Analyzer 

### ISSUE THREAD

**Issue by HerbertHBT** [forcedotcom/sfdx-scanner#1389] opened 2024-03-11 16:37 UTC
Hi Everyone,

I've started using the new null coalescing operator "??" made available in release Sping '24.
Doc reference: https://help.salesforce.com/s/articleView?id=release-notes.rn_apex_NullCoalescingOper.htm&release=248&type=5

The code works perfectly in sandboxes and prod, but I'm facing issues with the code analyzer scanner when the code contains the ?? operator.  It throws the following error:

PMDException: Error while parsing <class name>.cls Caused by: net.sourceforge.pmd.lang.ast.ParseException: apex.jorje.services.exception.ParseException: Syntax(error = UnexpectedToken(loc = (144, 61, 1071, 1072), token = '?'))

Thanks

**Comment by jag-j** [comment] 2024-03-13 17:48
This is a duplicate of #1293. We are fixing this with one of our upcoming releases. Thanks for reporting!

**Closed by jag-j** 2024-03-13 17:48 UTC
