### ISSUE TITLE
[BUG] ClassCastException

### ISSUE THREAD

**Issue by jaelee125** [forcedotcom/sfdx-scanner#1703] opened 2024-12-26 23:32 UTC
### Have you tried to resolve this issue yourself first?

Yes

### Bug Description

Getting an error setting an element in a List to null in a for loop

### Output / Logs

Error Message:
"InternalExecutionError","Graph Engine identified your source and sink, but you must manually verify that you have a sanitizer in this path. Then, add an engine directive to skip the path. Next, create a Github issue for the Code Analyzer team that includes the error and stack trace. After we fix this issue, check the Code Analyzer release notes for more info. Error and stacktrace: ClassCastException: class com.salesforce.graph.vertex.DefaultVertex cannot be cast to class com.salesforce.graph.vertex.VariableExpressionVertex (com.salesforce.graph.vertex.DefaultVertex and com.salesforce.graph.vertex.VariableExpressionVertex are in unnamed module of loader 'app'): com.salesforce.graph.vertex.AssignmentExpressionVertex.getLhs(AssignmentExpressionVertex.java:70);com.salesforce.graph.symbols.PathScopeVisitor.visit(PathScopeVisitor.java:739);com.salesforce.graph.symbols.DefaultSymbolProviderVertexVisitor.visit(DefaultSymbolProviderVertexVisitor.java:360);com.salesforce.graph.vertex.AssignmentExpressionVertex.visit(AssignmentExpressionVertex.java:27);com.salesforce.graph.ops.expander.ApexPathExpander.shouldVisitChildren(ApexPathExpander.java:573);com.salesforce.graph.ops.expander.ApexPathExpander.lambda$visit$1(ApexPathExpander.java:519)","https://developer.salesforce.com/docs/platform/salesforce-code-analyzer/guide/apexflsviolation-rule.html","InternalExecutionError","sfge"

### Steps To Reproduce

The following lines error out

List<String> fieldValues = new List<String>{'test', 'test1', ''};

for (Integer i = 0; i < fieldValues.size(); i++) {
	if (String.isBlank(fieldValues[i])) {
		fieldValues[i] = null;
	}
}

### Expected Behavior

There shouldn't be an error happening 

### Operating System

14.7.2

### Salesforce CLI Version

2.70.7

### Code Analyzer Plugin (@salesforce/sfdx-scanner) Version

4.7.0

### Java Version

openjdk version "19.0.1" 2022-10-18

### Workaround

I have not found a workaround

### Urgency

Low

**Comment by stephen-carter-at-sf** [comment] 2024-12-27 13:50
Duplicate of #1497

**Closed by stephen-carter-at-sf** 2024-12-27 13:50 UTC
