### ISSUE TITLE
[BUG]  ClassCastException, problem in a List

### ISSUE THREAD

**Issue by efwalter** [forcedotcom/sfdx-scanner#1143] opened 2023-08-03 21:34 UTC
**Describe the bug**
Graph Engine identified your source and sink, but you must manually verify that you have a sanitizer in this path. Then, add an engine directive to skip the path. Next, create a Github issue for the Code Analyzer team that includes the error and stack trace. After we fix this issue, check the Code Analyzer release notes for more info. Error and stacktrace: ClassCastException: class com.salesforce.graph.vertex.DefaultVertex cannot be cast to class com.salesforce.graph.vertex.VariableExpressionVertex (com.salesforce.graph.vertex.DefaultVertex and com.salesforce.graph.vertex.VariableExpressionVertex are in unnamed module of loader 'app'): com.salesforce.graph.vertex.AssignmentExpressionVertex.getLhs(AssignmentExpressionVertex.java:70);com.salesforce.graph.symbols.PathScopeVisitor.visit(PathScopeVisitor.java:719);com.salesforce.graph.symbols.DefaultSymbolProviderVertexVisitor.visit(DefaultSymbolProviderVertexVisitor.java:309);com.salesforce.graph.vertex.AssignmentExpressionVertex.visit(AssignmentExpressionVertex.java:27);com.salesforce.graph.ops.expander.ApexPathExpander.shouldVisitChildren(ApexPathExpander.java:573);com.salesforce.graph.ops.expander.ApexPathExpander.lambda$visit$1(ApexPathExpander.java:519)

**To Reproduce**
Running the scanner in a class is causing a issue in the following line:
`sFields[10] = fieldlist.get(sAlias + 'ProcessAddress').Field_Name__c;`
the problem is in the left part of the code in the sFields[10]

**Desktop:**
 - OS: macOS Ventura 13.4.1 (c)
 - Scanner Version 3.13.0

**Additional context**

"Workaround": 

"Urgency":

**Comment by jfeingold35** [comment] 2023-08-04 14:17
@efwalter , can you please post a more complete code snippet? It'll be hard for us to reproduce this one without knowing what `sFields` is supposed to be.

**Comment by efwalter** [comment] 2023-08-04 14:33
Sure:
`
for (CustomObject__c x : CustomSettings.getall().values()) {
            List<String> sFields = new List<String> ();
            
            String sAlias = x.NAMESPACE__Alias__c;
            String sNameSpace = x.NAMESPACE__Namespace__c;

           .....hidden content ....

            if (fieldlist.containskey(sAlias + 'ProcessAddress') && sFields != null && sFields.size()>10) {
                sFields[10] = fieldlist.get(sAlias + 'ProcessAddress').kwzd__Field_Name__c;
            }
`

**Comment by stephen-carter-at-sf** [comment] 2024-06-03 19:04
Marking this as a duplicate of https://github.com/forcedotcom/sfdx-scanner/issues/1497

**Closed by stephen-carter-at-sf** 2024-06-03 19:04 UTC
Labels: duplicate, BUG P3, SFGE
