### ISSUE TITLE
InternalExecutionError WHILE scanning my code with DFA 

### ISSUE THREAD

**Issue by ThamaraiAster** [forcedotcom/sfdx-scanner#1493] opened 2024-05-30 23:19 UTC
### Have you tried to resolve this issue yourself first?

Yes

### Bug Description

Severity- 3 | \classes\iq_CreateShipmentController.cls | Source Line  -- 73 | Source Column -- 38 | iq_CreateShipmentController | Method -- > calculatePalletSpots |   | InternalExecutionError
**ERROR Message :**
Graph Engine identified your source and sink, but you must manually verify that you have a sanitizer in this path. Then, add an engine directive to skip the path. Next, create a Github issue for the Code Analyzer team that includes the error and stack trace. After we fix this issue, check the Code Analyzer release notes for more info. Error and stacktrace: UnexpectedException: MethodCallExpressionVertex{fullMethodName=totalShipmentAmount.setScale, referenceVertex=LazyVertex{result=ReferenceExpression{properties={FirstChild=true, Names=[totalShipmentAmount], BeginLine=122, DefiningType_CaseSafe=iq_shipmentutils, LastChild=false, DefiningType=iq_ShipmentUtils, EndLine=122, Name_CaseSafe=totalshipmentamount, childIdx=0, BeginColumn=35, ReferenceType=METHOD, Name=totalShipmentAmount}}}, chainedNames=[totalShipmentAmount], properties={FirstChild=false, FullMethodName=totalShipmentAmount.setScale, BeginLine=122, FullMethodName_CaseSafe=totalshipmentamount.setscale, DefiningType_CaseSafe=iq_shipmentutils, LastChild=true, DefiningType=iq_ShipmentUtils, EndLine=122, MethodName_CaseSafe=setscale, childIdx=1, BeginColumn=55, MethodName=setScale}}: com.salesforce.graph.symbols.apex.ApexSimpleValue.apply(ApexSimpleValue.java:55);com.salesforce.graph.symbols.apex.ApexNumberValue.apply(ApexNumberValue.java:42);com.salesforce.graph.symbols.apex.ApexIntegerValue.apply(ApexIntegerValue.java:9);com.salesforce.graph.symbols.PathScopeVisitor.handleApexValueMethod(PathScopeVisitor.java:1487);com.salesforce.graph.symbols.PathScopeVisitor.afterVisit(PathScopeVisitor.java:1242);com.salesforce.graph.symbols.DefaultSymbolProviderVertexVisitor.afterVisit(DefaultSymbolProviderVertexVisitor.java:800)

### Steps To Reproduce

When i run dfa scan for the class "iq_CreateShipmentController" class , i am getting same kind of error for 29 classes in my code base.

### Expected Behavior

I expect a scanning result for my class. 

### Operating System

Window 11

### Salesforce CLI Version

@salesforce/cli  2.41.8

### Code Analyzer Plugin (@salesforce/sfdx-scanner) Version

@salesforce/sfdx-scanner 4.1.0 (latest-beta)

### Java Version

java version "21.0.2" 2024-01-16 LTS 

### Additional Context (Screenshots, Files, etc)

[iq_CreateShipmentController.cls.zip](https://github.com/user-attachments/files/15506592/iq_CreateShipmentController.cls.zip)
while scanning this file we were getting the problem.

### Workaround

No Work Around

### Urgency

High

**Comment by stephen-carter-at-sf** [comment] 2024-06-03 18:50
Marked this as a duplicate of https://github.com/forcedotcom/sfdx-scanner/issues/1497

**Closed by stephen-carter-at-sf** 2024-06-03 18:50 UTC
Labels: duplicate, SFGE
