### ISSUE TITLE
[BUG] "SfError: RetireJS: Unexpected token

### ISSUE THREAD

**Issue by ar-srinivas** [forcedotcom/sfdx-scanner#1639] opened 2024-10-01 10:51 UTC
### Have you tried to resolve this issue yourself first?

Yes

### Bug Description

sf scanner run fails with Retire JS Unexpected token Error

### Output / Logs

{
  "code": 1,
  "context": "Run",
  "commandName": "Run",
  "message": "RetireJS: /home/ubuntu/sf/sf/node_modules/@salesforce/sfdx-scanner/node_modules/retire/lib/cli.js:77\nconst jsrepolocation = (prg.jsrepo ?? \"'central'\")\n                                    ^\n\nSyntaxError: Unexpected token '?'\n    at wrapSafe (internal/modules/cjs/loader.js:915:16)\n    at Module._compile (internal/modules/cjs/loader.js:963:27)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n    at Module.load (internal/modules/cjs/loader.js:863:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:708:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)\n    at internal/main/run_main_module.js:17:47\n",
  "name": "SfError",
  "status": 1,
  "stack": "SfError: RetireJS: /home/ubuntu/sf/sf/node_modules/@salesforce/sfdx-scanner/node_modules/retire/lib/cli.js:77\nconst jsrepolocation = (prg.jsrepo ?? \"'central'\")\n                                    ^\n\nSyntaxError: Unexpected token '?'\n    at wrapSafe (internal/modules/cjs/loader.js:915:16)\n    at Module._compile (internal/modules/cjs/loader.js:963:27)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)\n    at Module.load (internal/modules/cjs/loader.js:863:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:708:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)\n    at internal/main/run_main_module.js:17:47\n\n    at RunAction.run (/home/ubuntu/sf/sf/node_modules/@salesforce/sfdx-scanner/lib/lib/actions/AbstractRunAction.js:103:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Run.run (/home/ubuntu/sf/sf/node_modules/@salesforce/sfdx-scanner/lib/lib/ScannerCommand.js:38:16)\n    at async Run._run (/home/ubuntu/sf/sf/node_modules/@salesforce/sfdx-scanner/node_modules/@oclif/core/lib/command.js:311:22)\n    at async Config.runCommand (/home/ubuntu/sf/node_modules/@oclif/core/lib/config/config.js:433:25)\n    at async run (/home/ubuntu/sf/node_modules/@oclif/core/lib/main.js:92:16)",
  "exitCode": 1,
  "warnings": [
    "We're continually improving Salesforce Code Analyzer. Tell us what you think! Give feedback at https://research.net/r/SalesforceCA",
    "Cataloger: Dropping XML file [META-INF/maven/net.sourceforge.pmd/pmd-visualforce/pom.xml] since its path does not conform to Rulesets or Category.",
    "Cataloger: Dropping XML file [META-INF/maven/net.sourceforge.pmd/pmd-apex/pom.xml] since its path does not conform to Rulesets or Category.",
    "The specified target wasn't processed by any engines. Use the --engine parameter to select a different engine or specify a different target. Specified target:xxxx."
  ]
}

### Steps To Reproduce

sfdx scanner run -t xxx -o xxx -f json --json

### Expected Behavior

It should return status as 0 and provide the analysis result

### Operating System

Ubuntu - Linux 6.5.0-1018-aws

### Salesforce CLI Version

@salesforce/cli/2.41.8

### Code Analyzer Plugin (@salesforce/sfdx-scanner) Version

@salesforce/sfdx-scanner 4.6.0 (user)

### Urgency

High

**Comment by stephen-carter-at-sf** [comment] 2024-10-01 15:23
@ar-srinivas Can you narrow down your target list to the one input file that is causing retire js to give this error? If so, can you then send me that file so we can reproduce? This will help us figure out if this is an issue with code analyzer or retire-js (where we can submit an issue over at https://github.com/RetireJS/retire.js to get this fixed).

**Comment by stephen-carter-at-sf** [comment] 2024-10-01 15:28
@ar-srinivas Also I just noticed your command that you listed above is `sfdx scanner ...` which we no longer support. Can you first try to install latest sf cli via `npm install -g @salesforce/cli@latest` or `sf update` and then use `sf scanner ...` instead.

**Comment by stephen-carter-at-sf** [comment] 2024-10-01 15:30
Lastly, how did you install the sfdx-scanner... it says `(user)` next to it. Did you try linking instead of installing? You should be installing plugins via `sf plugins install @salesforce/sfdx-scanner@latest` and not doing an npm install with a link.

**Comment by ar-srinivas** [comment] 2024-10-01 15:33
Installation of sf cli was done using the tar file on Linux server and used the same plugins command to install the scanner plugin.

I am getting the same issue with sf scanner and sfdx scanner commands.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stephen-carter-at-sf** [comment] 2024-10-01 15:37
@ar-srinivas Does the error occur when targetting any file? Or does it only occur on a specific file? If a specific file - then please share that file with us so we can reproduce. Currently we can't reproduce this issue.

**Comment by stephen-carter-at-sf** [comment] 2024-10-03 12:49
@ar-srinivas OK... can you then please answer my other questions. Can you reproduce this on any set of files? If not, then can you please narrow it down to a specific file that causes the problem and send me that file.

Also, have you tried installing not from tarball, but directly from npm?

**Comment by ar-srinivas** [comment] 2024-10-03 12:58
Thank you @stephen-carter-at-sf. 
I am using a set of files and it not easy to find a file which is causing this issue. I have aura, lwc, apex code in the files. 

As a standard process we are using the tarball installation not the npm.

**Comment by stephen-carter-at-sf** [comment] 2024-10-03 15:48
Well I am unable to reproduce this issue on any of our environments. Can you reproduce it locally on your machine or just on your server? Without narrowing down the problem a bit, we won't be able to help you and we'll need to close this issue since it isn't being reported by anyone else.

**Comment by ar-srinivas** [comment] 2024-10-04 03:20
I understand… I’m would suspect the node version might be causing this issue. When I run sf version, I could see a node version as 20+ but when I run node -v, I get it as 12+.
I trying to see how I can remove the old version and keep only the one come with sf cli.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Closed** 2024-10-04 13:07 UTC
Labels: Bug - Need more info
