### ISSUE TITLE
[Feature Request] Upgrade Apex Parser to support new Apex features such as the null coalesce operator

### ISSUE THREAD

**Issue by johnbelosf** [forcedotcom/sfdx-scanner#1293] opened 2023-12-20 16:59 UTC
Update apex parser (via PMD7) to support:

- Apex user mode
- Apex null coalesce `??` operator

**Comment by johnbelosf** [comment] 2024-01-23 16:32
@jamessimone definitely - I updated it. Thank you!

**Comment by codefriar** [comment] 2024-02-13 05:56
@johnbelosf  - Don't suppose there's a beta we can test? - Have some code using `??` and it's dying.

**Comment by stephen-carter-at-sf** [comment] 2024-02-15 13:35
Added --preview-pmd7 with https://github.com/forcedotcom/sfdx-scanner/pull/1359 to be released in march. Keeping this issue open though since PMD 7.0.0-rc4 doesn't support the null coalesce ?? operator still.

**Comment by jtryan0601** [comment] 2024-02-26 01:51
> @johnbelosf can we update the description on this one to include adding support for the null coalesce `??` operator? People will have access to that syntax with the release of Spring '24, but PMD currently chokes when scanning files using the null coalesce operator:
> 
> ```
> net.sourceforge.pmd.lang.ast.ParseException:
> apex.jorje.services.exception.ParseException:
> Syntax(error = UnexpectedToken(loc = (19, 82, 162, 163), token = '?'))
> ```

Hi, I'm wondering, is there a way to bypass the ParseException error? I tried adding //NOPMD but it looks like parsing happens before checking for that comment.

**Comment by mattlacey** [comment] 2024-03-01 16:49
As @jtryan0601 says, is there a way to bypass these errors? Trying to scan for security review and have a lot of code that's failing with "files-must-compile"

**Comment by johnbelo** [comment] 2024-03-01 17:29
@mattlacey we will release a preview version of PMD7 in our upcoming release, which is the week of the 11th March. It will support features such as user mode, but not the most recent features such as the null coalescing operator. Unfortunately there's no workaround in the meantime.

**Comment by johnbelosf** [comment] 2024-03-01 17:31
@mattlacey  we will release a preview version of PMD7 in our upcoming release, which is the week of the 11th March. It will support features such as user mode, but not the most recent features such as the null coalescing operator. Unfortunately there's no workaround in the meantime.

**Comment by stephen-carter-at-sf** [comment] 2024-03-22 21:47
Once we put #1403  into our 4.0.0 release (coming soon) then users will be able to leverage the new PMD7 that came out today. I confirmed that it has support for the null coalesce operator

**Closed by stephen-carter-at-sf** 2024-03-22 21:47 UTC
Labels: USER STORY, Roadmap

**Comment by jamessimone** [comment] 2024-03-25 14:15
@stephen-carter-at-sf I think this issue was auto-closed when #1403 was merged to `dev`, but shouldn't it really stay open until the public release of 4.0.0 is made?
