### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by kevanmoothien** [forcedotcom/sfdx-scanner#1252] opened 2023-11-27 08:03 UTC
### `scanner:run` Issue Template

Fill out this template to submit your Code Analyzer issue.

**Description**:
I am having the following issue when running the command `sfdx scanner:run --format html --target 'force-app/main/default/classes/*.cls' --outfile 'scan/apex_result.html'`. It seems that the file is not able to compile through the PMD framework. The line `insert as user newShare;` is causing this issue. 
```
	PMDException: Error while parsing /home/kevan/Desktop/ruby/sharinpix/sfdx/force-app/main/default/classes/ShareUtils.cls Caused by: net.sourceforge.pmd.lang.ast.ParseException: apex.jorje.services.exception.ParseException: Syntax(error = UnexpectedToken(loc = (104, 20, 1125, 1127), token = 'as'))
```

**Documentation**:

Here is the documentation: https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_classes_enforce_usermode.htm

**Steps To Reproduce**:

You can just run the command with the following class. 
```
global with sharing class ShareUtils {
    public String url;

    public void createShareRecord() {
        Share__c newShare = new Share__c(
            Link__c = url
        );
        try {
            insert as user newShare;
        } catch(Exception e) {
            
        }
    }
}
```

**Expected Behavior**:

It should not errored

**Screenshots**:

**Desktop**:

**Additional Context**:

**Workaround**:

**Urgency**:

**Comment by jfeingold35** [comment] 2023-11-27 14:12
Duplicate of #1026.

**Closed by jfeingold35** 2023-11-27 14:12 UTC
