### ISSUE TITLE
Scanner and VSCode plugin ignore Custom Metadata (XML) rules [BUG]

### ISSUE THREAD

**Issue by rsoesemann** [forcedotcom/sfdx-scanner#1202] opened 2023-09-30 21:21 UTC
I think I reported that many times but nobody really seems to care about this. Apex and Standard rules are only a small part of PMDs power. Many user rely on Custom XPath rules and rules for non Apex but XML files.

The SF Scanner needs to understand the ruleset (hierarchies) that define them and detect its issues

This can be all easily tested in this repo https://github.com/rsoesemann/unhappy-soup/tree/master/pmd

<img width="1610" alt="Screenshot_2023-09-30_at_23_15_50" src="https://github.com/forcedotcom/sfdx-scanner/assets/8180281/02d08b2f-568c-40fa-82f9-f9deae6b726b">

**Comment by rsoesemann** [comment] 2023-09-30 21:21
FYI @jfeingold35 @johnbelosf

**Comment by jfeingold35** [comment] 2023-10-02 03:48
@rsoesemann , unless I'm misunderstanding, this is a duplicate of #1104 , for which a fix was merged a few days ago. That fix will be going out on Tuesday with the 3.17.0 release.
Please see my comment on that issue.

**Closed by jfeingold35** 2023-10-02 03:48 UTC

**Comment by rsoesemann** [comment] 2023-10-02 09:31
Will this also fix the issue in the VS Code plugin? Then it is. Sorry.

**Comment by rsoesemann** [comment] 2023-10-05 19:33
<img width="1636" alt="Screenshot_2023-10-05_at_21_27_22" src="https://github.com/forcedotcom/sfdx-scanner/assets/8180281/3cd8683d-6fb6-4cd7-bcc9-495fd58bd9db">
@jfeingold35  After your recent update to the CLI the Scanner works but my VSCode extension still ignores them. Why?

**Comment by rsoesemann** [comment] 2023-10-05 19:36
Please reopen until I conform this works

**Comment by rsoesemann** [comment] 2023-10-06 11:49
Oh for sure. Then this is officially closed. ;-)
