### ISSUE TITLE
[BUG] Graph Engine - InternalExecutionError - UnexpectedException: StackOverflowError: null

### ISSUE THREAD

**Issue by ppillai7777** [forcedotcom/sfdx-scanner#1217] opened 2023-10-07 01:07 UTC
Ran the graph engine scan on our application source as shown below and report shows the InternalExecutionError rules.

sfdx scanner:run:dfa --format=csv --outfile=CodeAnalyzerDFA9.csv --target="./" --projectdir="./" --category="Security" --sfgejvmargs "-Xmx30g" --pathexplimit -1 --rule-thread-count 2 --rule-thread-timeout 21600000

Description column shows the following:
Graph Engine identified your source and sink, but you must manually verify that you have a sanitizer in this path. Then, add an engine directive to skip the path. Next, create a Github issue for the Code Analyzer team that includes the error and stack trace. After we fix this issue, check the Code Analyzer release notes for more info. Error and stacktrace: StackOverflowError: null: java.base/java.util.TreeMap.containsKey(TreeMap.java:233);com.salesforce.graph.symbols.PathScopeVisitor.getApexValue(PathScopeVisitor.java:337);com.salesforce.graph.symbols.PathScopeVisitor.getApexValue(PathScopeVisitor.java:352);com.salesforce.graph.symbols.PathScopeVisitor.getApexValue(PathScopeVisitor.java:352);com.salesforce.graph.symbols.PathScopeVisitor.getApexValue(PathScopeVisitor.java:352);com.salesforce.graph.symbols.PathScopeVisitor.getApexValue(PathScopeVisitor.java:352)

**Comment by stephen-carter-at-sf** [comment] 2024-06-03 19:01
Marking this as a duplicate of https://github.com/forcedotcom/sfdx-scanner/issues/1497

**Closed by stephen-carter-at-sf** 2024-06-03 19:01 UTC
Labels: duplicate, BUG P3, SFGE
