### ISSUE TITLE
[BUG] Getting ESLINT-CUSTOM violations on .cls files when using custom eslintconfig

### ISSUE THREAD

**Issue by aaronmorris** [forcedotcom/sfdx-scanner#810] opened 2022-09-02 17:57 UTC
**Describe the bug**
When I use a custom --eslintconfig, I start getting eslint-custom violations on apex class files

**To Reproduce**

1. Create a custom eslintrc.json files
2. run the scanner using the file: sfdx scanner:run --target "force-app/main/default/classes/MycClass.cls" --pmdconfig=apex_ruleset.xml --eslintconfig=.eslintrc.json --engine "pmd,eslint,retire-js,cpd" --outfile ./scanner-results.json

**Expected behavior**
Possible PMD violations, but no ESLINT violations

**Screenshots**
Output: [{"engine":"eslint-custom","fileName":"/home/runner/work/folder-name/folder-name/force-app/main/default/classes/MyClass.cls","violations":[{"line":1,"column":6,"severity":2,"message":"Parsing error: Missing semicolon. (1:6)","ruleName":null,"category":"","url":""}]}]

**Desktop (please complete the following information):**
 - OS: macOS 12.4
 - Scanner Version 3.4

**Additional context**
<details>
<summary>eslintrc.json</summary>
`{
  "root": true,
  "parser": "@babel/eslint-parser",
    "parserOptions": {
        "requireConfigFile": false,
        "babelOptions": {
            "parserOpts": {
                "plugins": ["classProperties", ["decorators", { "decoratorsBeforeExport": false }]]
            }
        }
    },

  "plugins": [
      "jest",
      "import",
      "@lwc/eslint-plugin-lwc"
  ],
  "extends": [
      "eslint:recommended",
      "@salesforce/eslint-config-lwc/recommended"
  ],

  "env": {
      "es6": true
  },
  "rules": {
      "no-unused-vars": "error",
      "array-bracket-newline": "error",
      "array-element-newline": "error",
      "arrow-body-style": "error",
      "arrow-parens": "error",
      "block-scoped-var": "error",
      "brace-style": "error",
      "camelcase": "error",
      "capitalized-comments": "error",
      "class-methods-use-this": "error",
      "comma-dangle": "error",
      "comma-spacing": "error",
      "dot-location": "error",
      "eol-last": "error",
      "eqeqeq": "error",
      "func-names": "error",
      "function-call-argument-newline": "error",
      "function-paren-newline": "error",
      "id-length": "error",
      "indent": ["error", 2],
      "keyword-spacing": "error",
      "line-comment-position": "error",
      "lines-around-comment": "error",
      "lines-between-class-members": "error",
      "max-len": ["error", 150],
      "max-statements": "error",
      "multiline-comment-style": "error",
      "multiline-ternary": "error",
      "newline-before-return": "error",
      "newline-after-var":"error",
      "newline-per-chained-call":"error",
      "no-alert": "error",
      "no-buffer-constructor": "error",
      "no-console": "error",
      "no-eval": "error",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-extra-label": "error",
      "no-extra-parens": "error",
      "no-iterator": "error",
      "no-inline-comments": "error",
      "no-lone-blocks": "error",
      "no-lonely-if": "error",
      "no-magic-numbers": "error",
      "no-mixed-spaces-and-tabs": "error",
      "no-proto": "error",
      "no-prototype-builtins": "error",
      "no-new-require": "error",
      "no-restricted-properties": ["error", {
          "object": "arguments",
          "property": "callee",
          "message": "arguments.callee is deprecated"
      }, {
          "object": "global",
          "property": "isFinite",
          "message": "Please use Number.isFinite instead"
      }, {
          "object": "self",
          "property": "isFinite",
          "message": "Please use Number.isFinite instead"
      }, {
          "object": "window",
          "property": "isFinite",
          "message": "Please use Number.isFinite instead"
      }, {
          "object": "global",
          "property": "isNaN",
          "message": "Please use Number.isNaN instead"
      }, {
          "object": "self",
          "property": "isNaN",
          "message": "Please use Number.isNaN instead"
      }, {
          "object": "window",
          "property": "isNaN",
          "message": "Please use Number.isNaN instead"
      }, {
          "property": "__defineGetter__",
          "message": "Please use Object.defineProperty instead."
      }, {
          "property": "__defineSetter__",
          "message": "Please use Object.defineProperty instead."
      }, {
          "object": "Math",
          "property": "pow",
          "message": "Use the exponentiation operator (**) instead."
      }],
      "no-self-compare": "error",
      "no-tabs": "error",
      "no-ternary": "error",
      "no-trailing-spaces": "error",
      "no-undef": "error",
      "no-undef-init": "error",
      "no-undefined": "error",
      "no-underscore-dangle": ["error", {"allowAfterThis": true}],
      "no-useless-computed-key": "error",
      "no-useless-escape": "error",
      "no-useless-call":"error",
      "no-useless-concat":"error",
      "no-useless-constructor":"error",
      "no-useless-rename":"error",
      "no-useless-return": "error",
      "object-curly-spacing": ["error", "always"],
      "object-property-newline": "error",
      "object-shorthand": "error",
      "one-var": "error",
      "padded-blocks": ["error", "never"],
      "prefer-arrow-callback": "error",
      "prefer-const": ["error", {
          "destructuring": "any",
          "ignoreReadBeforeAssign": true
      }],
      "prefer-destructuring": "error",
      "prefer-template": "error",
      "quote-props": "error",
      "quotes": ["error", "single"],
      "semi": "error",
      "space-before-blocks": "error",
      "space-before-function-paren": ["error", "never"],
      "space-in-parens": "error",
      "space-infix-ops": "error",
      "spaced-comment": "error",
      "sort-keys": "error",
      "sort-imports": "error",
      "template-curly-spacing": "error",
      "yoda": "error",
      "@lwc/lwc/consistent-component-name": "error",
      "@lwc/lwc/no-api-reassignments": "error",
      "@lwc/lwc/no-async-await": "error",
      "@lwc/lwc/no-async-operation": "error",
      "import/order": [
          "error",
          { "groups": ["builtin", "external", "internal", "parent", "index", "sibling", "object", "type"] }
      ]
  },

  "overrides": [
      {
          "files": [
              "**/@lwc/engine-core/**",
              "**/@lwc/engine-dom/**",
              "**/@lwc/synthetic-shadow/**"
          ],
          "rules": {
              "@lwc/lwc-internal/no-global-node": "error",
              "prefer-rest-params": "off",
              "prefer-spread": "off"
          }
      },
      {
          "files": [
              "**/__tests__/**",
              "**/__mocks__/**",
              "**/@lwc/integration-karma/**"
          ],

          "env": {
              "jest": true,
              "es6": true,
              "es2017": true,
              "es2020": true
          },

          "rules": {
              "jest/no-focused-tests": "error",
              "jest/valid-expect": "error",
              "jest/valid-expect-in-promise": "error"
          }
      },
      {
          "files": [
              "**/@lwc/integration-tests/**"
          ],

          "globals": {
              "$": true,
              "browser": true
          }
      },
      {
          "files": [
              "./*.js",
              "**/scripts/**",
              "**/jest.config.js"
          ],

          "env": {
              "node": true,
              "jest": true
          },

          "rules": {
              "no-console": "off"
          }
      }
  ]
}`
</details>

"Workaround": Don't include a custom eslintconfig

"Urgency": "Not business-stopping"

**Comment by jfeingold35** [comment] 2022-09-06 14:50
Hi @aaronmorris .
Thanks for bringing this to our attention.
If possible, could you please post the ESLInt config file you're using? That will help us figure out what the problem is.

**Comment by aaronmorris** [comment] 2022-09-06 15:07
@jfeingold35 - it's included int he collapsable additional content section above

**Comment by jfeingold35** [comment] 2022-09-06 16:04
@aaronmorris , thanks for pointing me to that.
We'll take a look and see what we can find. Stay tuned.

**Comment by jfeingold35** [comment] 2022-09-13 18:53
Hey @aaronmorris .
Sorry for the delay, but we believe we've figured out the cause. We'll add an item to our backlog to exclude `.cls` files from `eslint-custom` by default, but in the meantime you should be able to at least turn the parse errors into "File ignored because of a matching ignore pattern" warnings, by adding `"ignorePatterns": ["**/*.cls"]` to your custom config.

**Comment by jfeingold35** [comment] 2023-07-28 13:50
@DougMidgley , as mentioned in #1101 , we've pushed a fix for the noisy severity 1 violations. So we're going to close this issue for now.

**Closed by jfeingold35** 2023-07-28 13:50 UTC
Labels: BUG P3
