### ISSUE TITLE
[apex] Support null coalescing operator ?? (apex 60)

### ISSUE THREAD

**Issue by vctqs1** [forcedotcom/sfdx-scanner#1380] opened 2024-03-07 03:55 UTC
**Is your feature request related to an issue that you encountered with Salesforce Code Analyzer?**

Yes, this is new operator supported on apex 60
I am currently in the process of updating my Apex codebase to version 60, and I've introduced the use of the null coalescing operator ??, which is a new feature in Apex v60. 

**Describe the solution that you want:**

sfdx-scanner support ?? operator

**Describe alternatives that you've considered:**

N/A

**Additional Context:**

```
Analyzing with Salesforce Graph Engine. See /Users/vctqs1/.sfdx-scanner/sfge.log for details.... Error
Error (1): Graph engine encountered compilation errors. Fix the errors in /Users/vctqs1/Documents/developer/manabie/erp-salesforce/packages/auth/main/default/classes/PublicGroupHandler.cls and retry., Caused by:
Invalid syntax at 395:83. (Unexpected token '?'.)
Invalid syntax at 395:108. (Expecting ':' but was: ';')
```
<img width="840" alt="image" src="https://github.com/forcedotcom/sfdx-scanner/assets/30227910/b1cbf61c-8982-480d-87f1-b9cf42ac7970">

**Workaround:**

N/A
**Urgency:**

N/A

**Comment by stephen-carter-at-sf** [comment] 2024-03-22 21:49
Once #1395 goes out with our 4.0.0 release then our Salesforce Graph Engine will support the null coalescing operator and other apex v60 features.

**Comment by vctqs1** [comment] 2024-04-12 09:36
@stephen-carter-at-sf hi after getting upgrade to 4.0.0. I get this error
``

vctqs1@Thus-MacBook-Pro erp-salesforce % target="./packages" bash ./scripts/sfdx-scanner.sh

 ›   Warning: @salesforce/cli update available from 2.28.6 to 2.36.8.
(node:50045) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 ›   Warning: Plugin @salesforce/sfdx-scanner (4.0.0) differs from the version specified by sf (3.21.0)
Warning: We're continually improving Salesforce Code Analyzer. Tell us what you think! Give feedback at https://research.net/r/SalesforceCA
About to run PMD with custom config in ./rulesets/all-apex.xml. Please make sure that any custom rule references have already been added to the plugin through scanner:rule:add command.
Warning: PMD failed to evaluate against file '/Users/vctqs1/Documents/developer/manabie/erp-salesforce/packages/invoice/main/default/triggers/BillItemSyncEventUpdateTrigger.trigger'. Message: ParseException: Parse exception: com.google.summit.SummitAST$ParseException: Failed to parse /Users/vctqs1/Documents/developer/manabie/erp-salesforce/packages/invoice/main/default/triggers/BillItemSyncEventUpdateTrigger.trigger: Syntax error at 2:16: extraneous input 'void' expecting {'abstract', 'after', 'before', 'final', 'get', 'global', 'inherited', 'instanceof', 'override', 'private', 'protected', 'public', 'set', 'sharing', 'static', 'switch', 'testmethod', 'transient', 'trigger', 'virtual', 'webservice', 'when', 'with', 'without', 'list', 'map', 'system', 'user', 'select', 'count', 'from', 'as', 'using', 'scope', 'where', 'order', 'by', 'limit', 'and', 'or', 'not', 'avg', 'count_distinct', 'min', 'max', 'sum', 'typeof', 'end', 'then', 'like', 'in', 'includes', 'excludes', 'asc', 'desc', 'nulls', 'first', 'last', 'group', 'all', 'rows', 'view', 'having', 'rollup', 'tolabel', 'offset', 'data', 'category', 'at', 'above', 'below', 'above_or_below', 'security_enforced', 'system_mode', 'user_mode', 'reference', 'cube', 'format', 'tracking', 'viewstat', 'custom', 'standard', 'distance', 'geolocation', 'calendar_month', 'calendar_quarter', 'calendar_year', 'day_in_month', 'day_in_week', 'day_in_year', 'day_only', 'fiscal_month', 'fiscal_quarter', 'fiscal_year', 'hour_in_day', 'week_in_month', 'week_in_year', 'converttimezone', 'yesterday', 'today', 'tomorrow', 'last_week', 'this_week', 'next_week', 'last_month', 'this_month', 'next_month', 'last_90_days', 'next_90_days', 'last_n_days', 'next_n_days', 'n_days_ago', 'next_n_weeks', 'last_n_weeks', 'n_weeks_ago', 'next_n_months', 'last_n_months', 'n_months_ago', 'this_quarter', 'last_quarter', 'next_quarter', 'next_n_quarters', 'last_n_quarters', 'n_quarters_ago', 'this_year', 'last_year', 'next_year', 'next_n_years', 'last_n_years', 'n_years_ago', 'this_fiscal_quarter', 'last_fiscal_quarter', 'next_fiscal_quarter', 'next_n_fiscal_quarters', 'last_n_fiscal_quarters', 'n_fiscal_quarters_ago', 'this_fiscal_year', 'last_fiscal_year', 'next_fiscal_year', 'next_n_fiscal_years', 'last_n_fiscal_years', 'n_fiscal_years_ago', IntegralCurrencyLiteral, 'find', 'email', 'name', 'phone', 'sidebar', 'fields', 'metadata', 'pricebookid', 'network', 'snippet', 'target_length', 'division', 'returning', 'listview', '@', Identifier}
Syntax error at 2:21: mismatched input 'handleUpdate' expecting '.'
Syntax error at 2:33: missing ';' at '('
Syntax error at 4:4: mismatched input 'Map' expecting {'after', 'before', 'get', 'inherited', 'instanceof', 'set', 'sharing', 'switch', 'transient', 'trigger', 'when', 'with', 'without', 'system', 'user', 'select', 'count', 'from', 'as', 'using', 'scope', 'where', 'order', 'by', 'limit', 'and', 'or', 'not', 'avg', 'count_distinct', 'min', 'max', 'sum', 'typeof', 'end', 'then', 'like', 'in', 'includes', 'excludes', 'asc', 'desc', 'nulls', 'first', 'last', 'group', 'all', 'rows', 'view', 'having', 'rollup', 'tolabel', 'offset', 'data', 'category', 'at', 'above', 'below', 'above_or_below', 'security_enforced', 'system_mode', 'user_mode', 'reference', 'cube', 'format', 'tracking', 'viewstat', 'custom', 'standard', 'distance', 'geolocation', 'calendar_month', 'calendar_quarter', 'calendar_year', 'day_in_month', 'day_in_week', 'day_in_year', 'day_only', 'fiscal_month', 'fiscal_quarter', 'fiscal_year', 'hour_in_day', 'week_in_month', 'week_in_year', 'converttimezone', 'yesterday', 'today', 'tomorrow', 'last_week', 'this_week', 'next_week', 'last_month', 'this_month', 'next_month', 'last_90_days', 'next_90_days', 'last_n_days', 'next_n_days', 'n_days_ago', 'next_n_weeks', 'last_n_weeks', 'n_weeks_ago', 'next_n_months', 'last_n_months', 'n_months_ago', 'this_quarter', 'last_quarter', 'next_quarter', 'next_n_quarters', 'last_n_quarters', 'n_quarters_ago', 'this_year', 'last_year', 'next_year', 'next_n_years', 'last_n_years', 'n_years_ago', 'this_fiscal_quarter', 'last_fiscal_quarter', 'next_fiscal_quarter', 'next_n_fiscal_quarters', 'last_n_fiscal_quarters', 'n_fiscal_quarters_ago', 'this_fiscal_year', 'last_fiscal_year', 'next_fiscal_year', 'next_n_fiscal_years', 'last_n_fiscal_years', 'n_fiscal_years_ago', IntegralCurrencyLiteral, 'find', 'email', 'name', 'phone', 'sidebar', 'fields', 'metadata', 'pricebookid', 'network', 'snippet', 'target_length', 'division', 'returning', 'listview', Identifier}
Syntax error at 4:7: extraneous input '<' expecting {'after', 'before', 'get', 'inherited', 'instanceof', 'set', 'sharing', 'switch', 'transient', 'trigger', 'when', 'with', 'without', 'system', 'user', 'select', 'count', 'from', 'as', 'using', 'scope', 'where', 'order', 'by', 'limit', 'and', 'or', 'not', 'avg', 'count_distinct', 'min', 'max', 'sum', 'typeof', 'end', 'then', 'like', 'in', 'includes', 'excludes', 'asc', 'desc', 'nulls', 'first', 'last', 'group', 'all', 'rows', 'view', 'having', 'rollup', 'tolabel', 'offset', 'data', 'category', 'at', 'above', 'below', 'above_or_below', 'security_enforced', 'system_mode', 'user_mode', 'reference', 'cube', 'format', 'tracking', 'viewstat', 'custom', 'standard', 'distance', 'geolocation', 'calendar_month', 'calendar_quarter', 'calendar_year', 'day_in_month', 'day_in_week', 'day_in_year', 'day_only', 'fiscal_month', 'fiscal_quarter', 'fiscal_year', 'hour_in_day', 'week_in_month', 'week_in_year', 'converttimezone', 'yesterday', 'today', 'tomorrow', 'last_week', 'this_week', 'next_week', 'last_month', 'this_month', 'next_month', 'last_90_days', 'next_90_days', 'last_n_days', 'next_n_days', 'n_days_ago', 'next_n_weeks', 'last_n_weeks', 'n_weeks_ago', 'next_n_months', 'last_n_months', 'n_months_ago', 'this_quarter', 'last_quarter', 'next_quarter', 'next_n_quarters', 'last_n_quarters', 'n_quarters_ago', 'this_year', 'last_year', 'next_year', 'next_n_years', 'last_n_years', 'n_years_ago', 'this_fiscal_quarter', 'last_fiscal_quarter', 'next_fiscal_quarter', 'next_n_fiscal_quarters', 'last_n_fiscal_quarters', 'n_fiscal_quarters_ago', 'this_fiscal_year', 'last_fiscal_year', 'next_fiscal_year', 'next_n_fiscal_years', 'last_n_fiscal_years', 'n_fiscal_years_ago', IntegralCurrencyLiteral, 'find', 'email', 'name', 'phone', 'sidebar', 'fields', 'metadata', 'pricebookid', 'network', 'snippet', 'target_length', 'division', 'returning', 'listview', Identifier}
Syntax error at 4:25: mismatched input '>' expecting {';', ',', '='}
```
at line 2 is `  public static void handleUpdate(List<Sync_Event__c> updatedRecords, Map<Id, Sync_Event__c> oldMap) {`
<img width="1240" alt="image" src="https://github.com/forcedotcom/sfdx-scanner/assets/30227910/3b3469bf-3aec-4bd1-865d-35f2e7ea44fc">

Could you help a have look at this, please?

**Comment by stephen-carter-at-sf** [comment] 2024-09-05 17:31
Can you please give me more code to work with so that I can reproduce this? It's best to reduce down your code to a single file that you can share that reproduces the issue.

**Comment by abhidev1108** [comment] 2024-09-06 09:56
Also, this is the PMD analysis result running in my Pull request pipeline, We are using Azure DevOps

ERROR running scanner:run:  Sep 05, 2024 5:26:15 PM net.sourceforge.pmd.PMD runPmd
WARNING: Some deprecated options were used on the command-line, including -rulesets
Sep 05, 2024 5:26:15 PM net.sourceforge.pmd.PMD runPmd
WARNING: Consider replacing it with --rulesets (or -R)
Sep 05, 2024 5:26:15 PM net.sourceforge.pmd.util.log.internal.SimpleMessageReporter logImpl
SEVERE: Cannot load ruleset ./pmd/ruleset/apexRuleset.xml: Cannot resolve rule/ruleset reference 'rulesets/apex/bestpractices.xml/SoqlWithinLoops'.  Make sure the resource is a valid file or URL and is on the CLASSPATH. Use --debug (or a fine log level) to see the current classpath.
Sep 05, 2024 5:26:15 PM net.sourceforge.pmd.util.log.internal.SimpleMessageReporter logImpl
WARNING: No rules found. Maybe you misspelled a rule name? (./pmd/ruleset/apexRuleset.xml)

**Comment by stephen-carter-at-sf** [comment] 2024-09-06 16:14
OK, this thread is getting confusing due to all the different issues you are reporting. Let's keep one issue per thread. The thread started with possible issues with the 'run dfa' command. But now you are moving into PMD.

Given your code snippet I am unable to reproduce at all - either with the `run` command or with the `run dfa` command. Have you tried upgrading to the latest instead of using 4.0.0 (which was still in beta at the time).

By the way... PMD is bundled with our sfdx-scanner plugin... so you installing PMD on your machine isn't what we use.

So try doing:
```
sf update
sf plugins install @salesforce/sfdx-scanner@latest
```
and then try to reproduce.

---


Regarding your next question. The error message from PMD seems to imply you are referencing a bad rule reference:
```
rulesets/apex/bestpractices.xml/SoqlWithinLoops
```
This isn't salesforce code analyzer... this is an error from PMD. With PMD7... they stopped using the rulesets folder and instead moved to their category folder. And I believe SoqlWithinLoops doesn't exist. With PMD7 they moved AvoidSoqlInLoops to instead be OperationWithLimitsInLoop. So you should be referencing this rule as 
```
<rule ref="category/apex/performance.xml/OperationWithHighCostInLoop" />
```
As it is documented over at https://pmd.github.io/pmd/pmd_rules_apex_performance.html#operationwithlimitsinloop

**Comment by stephen-carter-at-sf** [comment] 2024-09-06 16:16
Closing once again, because I'm unable to reproduce. Please open a new issue if you want to further discuss with more clear repro steps.

**Closed by stephen-carter-at-sf** 2024-09-06 16:16 UTC
Labels: USER STORY
