### ISSUE TITLE
[BUG] UnexpectedException: Did not expect NOT_A_MATCH when ranking parameter match

### ISSUE THREAD

**Issue by simon-nc-squared** [forcedotcom/sfdx-scanner#1245] opened 2023-11-15 15:05 UTC
**Description:**
When running the DFA scanner on our code we are getting the error `UnexpectedException: Did not expect NOT_A_MATCH when ranking parameter match`. I've managed to simplify the code to the below example that reproduces the issue. It seems to be related to the ternary operator because if I switch the condition around it passes.

**Documentation:**
```
UnexpectedException: Did not expect NOT_A_MATCH when ranking parameter match. parameterType = SObject, type = OrderedTreeSet{internalList=[NULL, Object]}:
com.salesforce.graph.ops.TypeableUtil.rankParameterMatch(TypeableUtil.java:211);
com.salesforce.graph.vertex.Typeable.rankParameterMatch(Typeable.java:41);
com.salesforce.graph.ops.MethodTypeMatchUtil.getMatchRank(MethodTypeMatchUtil.java:191);
com.salesforce.graph.ops.MethodTypeMatchUtil.parameterTypesMatch(MethodTypeMatchUtil.java:128);
com.salesforce.graph.ops.MethodUtil.getInvoked(MethodUtil.java:358);
com.salesforce.graph.ops.MethodUtil.getInvoked(MethodUtil.java:158)
```
[sfge.log](https://github.com/forcedotcom/sfdx-scanner/files/13366221/sfge.log)

**Steps To Reproduce:**
The below example will cause the exception
```
public with sharing class NotAMatchIssue {

    @RemoteAction @ReadOnly
    public static void test1(Id accountId) {      
        Account oldAccount = getAccountById(accountId); 
        cloneSObjectForUpdate(oldAccount);
    }
    
    public static Account getAccountById(Id accountId) {
        List<Account> results = Database.query('SELECT Id, Name FROM Account WHERE Id = :accountId', AccessLevel.USER_MODE);
        return results.size() < 1 ? null : results[0];
    }
    
    public static void cloneSObjectForUpdate(SObject objectToClone) {   
    }
}
```
Changing the `getAccountById` method to `return results.size() == 1 ? results[0] : null;` allows the scan to pass

**Expected Behaviour:**
For the scanner to pass for this scenario.

**Desktop:**
- Operating System. Example: Windows 10
- Code Analyzer version. Example: v3.18.0
- Salesforce CLI version. Example: @salesforce/cli/2.16.8

**Comment by jfeingold35** [comment] 2023-11-15 15:34
@simon-nc-squared , I believe this is a duplicate of #1195.

**Closed by jfeingold35** 2023-11-15 15:34 UTC
