### ISSUE TITLE
[BUG] RetireJS can not be found

### ISSUE THREAD

**Issue by yurybond** [forcedotcom/sfdx-scanner#672] opened 2022-05-06 10:45 UTC
**Describe the bug**
After fresh install of sfdx-scanner v3.0.3 on MacOS (M1 Pro) and first ty of scanning got the following error

`ERROR running scanner:run:  RetireJS: env: node: No such file or directory`

**To Reproduce**
1. Install salesforce cli from .pkg file (https://developer.salesforce.com/tools/sfdxcli)2. 
2. Install  sfdx-scanner 
`sfdx plugins:install @salesforce/sfdx-scanner`
3. Uninstall stable version of scanner
`sfdx plugins:uninstall @salesforce/sfdx-scanner`
4. Install pilot version (v3.0.3)
`sfdx plugins:install @salesforce/sfdx-scanner@latest-pilot`
5. Run scanning with predefined rules
`sfdx scanner:run -f html -o scanning_results.html -t force-app/main/default/`
6. See the error
`ERROR running scanner:run:  RetireJS: env: node: No such file or directory`

**Expected behavior**
I expected file in html format with results of scanning to be generated

**Screenshots**
<img width="850" alt="retireJs error" src="https://user-images.githubusercontent.com/563683/167117380-ec3cd83c-a129-42bd-ab95-a1ed83db7720.png">

**Desktop (please complete the following information):**
 - OS: MacOS (M1 Pro)
 - Java JDK: OpenJDK Runtime Environment Zulu17.34+19-CA
 - Scanner Version: v3.0.3 (pilot)
 - No NodeJS installed - the salesforce CLI was installed from .pkg 

**Additional context**
N/A

"Workaround": Have you found any ways to sidestep the problem?
No

"Urgency": How severe is this problem? "Business stopping" vs "Not business-stopping".
Not business-stopping

**Comment by jfeingold35** [comment] 2022-05-06 15:21
Hi @yurybond . Thanks for letting us know about this.
It looks like the issue isn't that RetireJS isn't being found, but that it can't find a version of node to run. Could you please try running RetireJS on the `latest` branch instead of `latest-pilot`? You can do that by running the following commands:
`> sfdx plugins:uninstall @salesforce/sfdx-scanner`
`> sfdx plugins:install @salesforce/sfdx-scanner`
`> sfdx scanner:run -f html -o scanning_results.html -t force-app/main/default/ --engine retire-js`

Please try that, and let us know if it works or if you still see the same error.
Thanks!

**Comment by jfeingold35** [comment] 2022-05-06 17:27
Also, @yurybond , could you please do the following?
1. Run `sfdx -v` and take note of which version of `node` is included.
2. Run `sfdx update`, and then run `sfdx -v` again, and then finally try the original `sfdx scanner:run` command again.
Doing that should rule out (or help identify) any possible problems with SFDX itself.

**Comment by FeldhackerChrisPFG** [comment] 2022-05-10 21:35
Same problem on Windows with v3.0.3
![image](https://user-images.githubusercontent.com/69258451/167725714-627d6293-7e82-4692-a9aa-821d5cc794d4.png)

**Comment by jfeingold35** [comment] 2022-05-11 00:13
@FeldhackerChrisPFG , could you please try the steps I described above and let us know if those fix it?

**Comment by FeldhackerChrisPFG** [comment] 2022-05-11 19:19
@jfeingold35 I did try the steps described and the problem still occurs.

**Comment by rmohan20** [comment] 2022-05-11 23:38
Thanks for letting us know.
We are looking into this issue and we'll post an update as soon as we have one.

**Comment by jfeingold35** [comment] 2022-05-16 18:46
@yurybond , @FeldhackerChrisPFG , we're still working on fixing this, but could you please try the following workaround and let us know if you are unblocked?
In your home directory, there should be a `.sfdx-scanner` folder, containing a file called `Config-pilot.json`. If you open that file in an editor and change the entry for `engines.retire-js.disabled` from `false` to `true`, then RetireJS will be disabled by default and you should only encounter the error if you include the `--engine retire-js` argument in relevant commands.

**Comment by FeldhackerChrisPFG** [comment] 2022-05-16 19:38
@jfeingold35 Confirmed -- the error does not occur with the workaround in place.

**Comment by ranekere-sfdc** [comment] 2022-05-26 17:24
@FeldhackerChrisPFG @yurybond the fix for this issue was released yesterday. Could you please update the plugin version and let us know if are still experiencing it?

**Comment by FeldhackerChrisPFG** [comment] 2022-05-26 17:48
@ranekere-sfdc Problem is fixed on Windows now with plugin v3.1.2.
![image](https://user-images.githubusercontent.com/69258451/170545972-46133b8e-b3f4-4e3d-b78e-84b78316284c.png)

**Closed** 2022-05-27 18:16 UTC
