### ISSUE TITLE
insert as user - Error while parsing

### ISSUE THREAD

**Issue by initdotd** [forcedotcom/sfdx-scanner#1091] opened 2023-06-07 13:03 UTC
**Describe the bug**
When a class contains "as user" on DML, the scanner fails to parse the file.  Removing "as user" from the line, allows the parser to work and thus scan the file.

FAIL
`insert as user myAccount;`

PASS
`insert myAccount;`

**To Reproduce**
Create an apex class and use the "as user" on an operation.
`
insert as user someSObject;
`

**Expected behavior**
The scanner should correctly parse the apex class.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - sfdx-cli/7.203.6 win32-x64 node-v18.16.0
 - @salesforce/sfdx-scanner 3.13.0

**Additional context**
Fails both running locally or via CI.

"Workaround": Have you found any ways to sidestep the problem?
Only changing the code to use Database.insert()

"Urgency": How severe is this problem? "Business stopping" vs "Not business-stopping".
Not business-stopping, but does create technical debt as no code can be promoted without passing static code analysis.

**Comment by initdotd** [comment] 2023-06-08 03:27
Hi @jfeingold35, I'm using `scanner:run`

It is being run via GitHub actions against a PR diff.  Here is the full command for reference.
`sfdx scanner:run -t ./changed_files -s 3`

Thanks in advance!

**Comment by jfeingold35** [comment] 2023-06-08 19:32
Hey @initdotd,
Looks like the issue here is that PMD v6 is using an outdated version of the Apex language model that doesn't support the `as user` syntax. The PMD community has recently stopped releasing new versions of v6 in favor of finishing v7, and we're in the process of assessing the level of effort required to update to v7, as well as whether it will fix issues like this.
We'll provide updates as the situation develops, but in the meantime stay tuned. Thanks for your understanding and your patience.

**Comment by jaelee125** [comment] 2023-09-18 21:22
Do you have any update regarding this issue?

**Comment by jfeingold35** [comment] 2023-09-18 21:35
@jaelee125 , as has (I believe) been mentioned elsewhere, our initial plan was to wait until PMD 7 was generally available before updating to it. However, PMD 7 is still in pre-release, and looks like it might remain in pre-release for the near future.
That said, we recognize that the delay on this has been longer than anyone anticipated. I can't really provide too many details, but I can say that we're assessing our options to see if there's a way we can close this in a reasonable timeframe.
In the meantime, we appreciate your patience.

**Comment by jfeingold35** [comment] 2023-10-16 17:26
Closing this issue as a duplicate of #1026 .

**Closed by jfeingold35** 2023-10-16 17:26 UTC
