### ISSUE TITLE
[BUG] Cannot Install Scanner Plugin

### ISSUE THREAD

**Issue by max-litify** [forcedotcom/sfdx-scanner#1310] opened 2024-01-08 15:46 UTC
### `scanner run` Issue Template
**Description**:
I cannot install the scanner. When I run `sf plugins install @salesforce/sfdx-scanner@latest` I get the following error:
```
Polling for new version(s) to become available on npm... done
Successfully validated digital signature for @salesforce/sfdx-scanner.
Finished digital signature check.
Installing plugin @salesforce/sfdx-scanner@latest... failed
 ›   Warning: @salesforce/sfdx-scanner > @salesforce/command@5.3.9: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
    Error: /usr/local/lib/node_modules/@salesforce/cli/node_modules/yarn/bin/yarn.js add @salesforce/sfdx-scanner@latest --non-interactive --mutex=file:/Users/maxstackhouse/.local/share/sf/yarn.lock 
    --preferred-cache-folder=/Users/maxstackhouse/Library/Caches/sf/yarn --check-files exited with code 1
```

It appears that a dependency is having issues. I'm on the latest version of the cli and node
```
% sf -v
@salesforce/cli/2.22.7 darwin-x64 node-v19.6.0
% node -v
v19.6.0
```

**Documentation**:

**Steps To Reproduce**:

**Expected Behavior**:

**Screenshots**:

**Desktop**:

macOs 13.6.1
sf -v: `@salesforce/cli/2.22.7 darwin-x64 node-v19.6.0`
node -v: `v19.6.0`

**Additional Context**:

**Workaround**:

**Urgency**:

**Comment by jfeingold35** [comment] 2024-01-08 16:04
@max-litify , I'm able to successfully install, as seen in the below screenshot.
![Screen Shot 2024-01-08 at 10 00 25 AM](https://github.com/forcedotcom/sfdx-scanner/assets/4054488/aa82c1c2-7e75-44af-aebf-a36b8242d8f9)
This error is one we've observed before. It seems to be some weird intermittent thing. If you try again, you should be able to get past it. You may also wish to try quitting and re-opening your terminal, as we've seen it resolve after that too.

**Comment by max-litify** [comment] 2024-01-08 16:40
@jfeingold35  I got the plugin to install, but I needed to switch to node `v18.1.0` instead of `v19.6.0`. Seems like there are some issues with Node v19 in some of the dependencies

**Comment by tpgken** [comment] 2024-01-11 04:55
I also experience the same issue in the GitHub action as part of the maintenance of the company's system.
Our Github action using linux

**Comment by KevinGossentCap** [comment] 2024-01-30 14:26
I'm adding some information that might make the issue part of oclif instead of sfdx-scanner but both are Salesforce teams.
I've found that the very last step of the install or link of a plugin is in "oclif/plugin-plugins".
I found that in the file "src/plugins.ts" it forces the verbose flag to false.
I tried forcing it to true and the result is that, even when setting the registry to npmjs, there are some packages (which exist in npm registry) that are still forced to be taken from yarnpkg registry !!!

`sf plugins install @salesforce/sfdx-scanner
Polling for new version(s) to become available on npm... done
Successfully validated digital signature for @salesforce/sfdx-scanner.
Finished digital signature check.
C:\Users\wh6533\AppData\Local\sf\node_modules\@salesforce\sfdx-scanner: C:\Users\wh6533\AppData\Local\Programs\node-v20-win-x64\node_modules\@salesforce\cli\node_modules\yarn\bin\yarn.js --prod --non-interactive --mutex=file:C:\Users\wh6533\AppData\Local\sf\node_modules\@salesforce\sfdx-scanner\yarn.lock --preferred-cache-folder=C:\Users\wh6533\AppData\Local\sf\yarn --check-files --verbose --registry=https://registry.npmjs.org/yarn install v1.22.21
verbose 0.252277 Checking for configuration file "C:\\Users\\wh6533\\AppData\\Local\\sf\\node_modules\\@salesforce\\sfdx-scanner\\.npmrc".
verbose 0.2526221 Checking for configuration file "C:\\Users\\wh6533\\.npmrc".
verbose 0.2528352 Checking for configuration file "C:\\Users\\wh6533\\AppData\\Local\\Programs\\node-v20-win-x64\\etc\\npmrc".
verbose 0.2530268 Checking for configuration file "C:\\Users\\wh6533\\AppData\\Local\\sf\\node_modules\\@salesforce\\sfdx-scanner\\.npmrc".
verbose 0.2532565 Checking for configuration file "C:\\Users\\wh6533\\AppData\\Local\\sf\\node_modules\\@salesforce\\.npmrc".
verbose 0.2534929 Checking for configuration file "C:\\Users\\wh6533\\AppData\\Local\\sf\\node_modules\\.npmrc".
verbose 0.2537196 Checking for configuration file "C:\\Users\\wh6533\\AppData\\Local\\sf\\.npmrc".
verbose 0.2539804 Checking for configuration file "C:\\Users\\wh6533\\AppData\\Local\\.npmrc".
verbose 0.2542275 Checking for configuration file "C:\\Users\\wh6533\\AppData\\.npmrc".
verbose 0.2544709 Checking for configuration file "C:\\Users\\wh6533\\.npmrc".
verbose 0.2547559 Checking for configuration file "C:\\Users\\.npmrc".
verbose 0.2555948 Checking for configuration file "C:\\Users\\wh6533\\AppData\\Local\\sf\\node_modules\\@salesforce\\sfdx-scanner\\.yarnrc".
verbose 0.2558186 Checking for configuration file "C:\\Users\\wh6533\\.yarnrc".
verbose 0.2561012 Found configuration file "C:\\Users\\wh6533\\.yarnrc".
verbose 0.2568981 Checking for configuration file "C:\\Users\\wh6533\\AppData\\Local\\Programs\\node-v20-win-x64\\etc\\yarnrc".
verbose 0.2572891 Checking for configuration file "C:\\Users\\wh6533\\AppData\\Local\\sf\\node_modules\\@salesforce\\sfdx-scanner\\.yarnrc".
verbose 0.2574923 Checking for configuration file "C:\\Users\\wh6533\\AppData\\Local\\sf\\node_modules\\@salesforce\\.yarnrc".
verbose 0.2577055 Checking for configuration file "C:\\Users\\wh6533\\AppData\\Local\\sf\\node_modules\\.yarnrc".
verbose 0.2579108 Checking for configuration file "C:\\Users\\wh6533\\AppData\\Local\\sf\\.yarnrc".
verbose 0.2580162 Checking for configuration file "C:\\Users\\wh6533\\AppData\\Local\\.yarnrc".
verbose 0.258115 Checking for configuration file "C:\\Users\\wh6533\\AppData\\.yarnrc".
verbose 0.2584452 Checking for configuration file "C:\\Users\\wh6533\\.yarnrc".
verbose 0.2586837 Found configuration file "C:\\Users\\wh6533\\.yarnrc".
verbose 0.2592012 Checking for configuration file "C:\\Users\\.yarnrc".
verbose 0.2654388 current time: 2024-01-30T14:04:02.108Z
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
verbose 0.6598451 Performing "GET" request to "https://registry.yarnpkg.com/@babel/helpers/-/helpers-7.23.7.tgz".
verbose 0.7261179 Performing "GET" request to "https://registry.yarnpkg.com/@jridgewell/trace-mapping/-/trace-mapping-0.3.20.tgz".
verbose 0.7465465 Performing "GET" request to "https://registry.yarnpkg.com/electron-to-chromium/-/electron-to-chromium-1.4.618.tgz".
verbose 0.7481687 Performing "GET" request to "https://registry.yarnpkg.com/caniuse-lite/-/caniuse-lite-1.0.30001572.tgz".
verbose 0.7640181 Performing "GET" request to "https://registry.yarnpkg.com/@oclif/core/-/core-3.16.0.tgz".
verbose 0.7852498 Performing "GET" request to "https://registry.yarnpkg.com/tsconfck/-/tsconfck-3.0.1.tgz".
verbose 0.8659322 Performing "GET" request to "https://registry.yarnpkg.com/@babel/runtime/-/runtime-7.23.7.tgz".
verbose 0.8716054 Performing "GET" request to "https://registry.yarnpkg.com/@babel/runtime-corejs3/-/runtime-corejs3-7.23.7.tgz".
verbose 2.022596 Error: self-signed certificate in certificate chain
    at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
    at TLSSocket.emit (node:events:518:28)
    at TLSSocket._finishInit (node:_tls_wrap:1085:8)
    at ssl.onhandshakedone (node:_tls_wrap:871:12)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Installing plugin @salesforce/sfdx-scanner@latest... failed
 »   Warning: @salesforce/sfdx-scanner > retire > read-installed > debuglog@1.0.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
    Error: C:\Users\wh6533\AppData\Local\Programs\node-v20-win-x64\node_modules\@salesforce\cli\node_modules\yarn\bin\yarn.js --prod --non-interactive --mutex=file:C:\Users\wh6533\AppData\Local\sf\node_modules\@salesforce\sfdx-scanner\yarn.lock
    --preferred-cache-folder=C:\Users\wh6533\AppData\Local\sf\yarn --check-files --verbose --registry=https://registry.npmjs.org/ exited with code 1`

and it only happens from sfdx-scanner 3.18 (3.17 was ok and installing properly)

**Comment by KevinGossentCap** [comment] 2024-02-19 08:19
Hi @johnbelosf , I can confirm that the installation works like a charm after installing the beta version of @oclif/plugin-plugins

**Comment by stephen-carter-at-sf** [comment] 2024-03-01 22:01
Hey folks, we are starting to triage some of these bugs. For this one, we are wondering if it is still an issue with the latest version of the salesforce cli?

This doesn't quite look like a bug with the sfdx-scanner plugin per se, if anything it would be an issue for the https://github.com/oclif/oclif repo or the https://github.com/salesforcecli/cli repo in my opinion. 

@max-litify @KevinGossentCap Does it make sense to move this issue to one of those repos and close this issue?

**Closed** 2024-03-01 22:37 UTC
Labels: BUG P3
