### ISSUE TITLE
[BUG] InternalExecutionError when running getChildObjects method

### ISSUE THREAD

**Issue by RonanWilliams1** [forcedotcom/sfdx-scanner#1340] opened 2024-01-31 13:15 UTC
Description:

Graph Engine identified your source and sink, but you must manually verify that you have a sanitizer in this path. Then, add an engine directive to skip the path. Next, create a Github issue for the Code Analyzer team that includes the error and stack trace. After we fix this issue, check the Code Analyzer release notes for more info. Error and stacktrace: UnexpectedException: ApexStringValue{ value=Optional.empty} ApexValue(ApexStringValue) {status=INITIALIZED, declarationVertex=VariableDeclaration{properties={FirstChild=false, BeginLine=464, Type=String, DefiningType_CaseSafe=relatablecore, LastChild=true, DefiningType=RelatableCore, EndLine=464, Name_CaseSafe=namefield, childIdx=1, BeginColumn=16, Name=nameField}}, valueVertex=LiteralExpression{properties={FirstChild=true, BeginLine=464, DefiningType_CaseSafe=relatablecore, LastChild=false, DefiningType=RelatableCore, EndLine=464, childIdx=0, LiteralType=NULL, BeginColumn=28}}, resolvedValues={}, returnedFrom=null, invocableExpression=null, method=null}: com.salesforce.graph.ops.ApexValueUtil.getTypeValue(ApexValueUtil.java:376);com.salesforce.graph.ops.ApexValueUtil.convertApexValueToString(ApexValueUtil.java:305);com.salesforce.rules.fls.apex.operations.FlsValidationRepresentation.addField(FlsValidationRepresentation.java:122);com.salesforce.rules.fls.apex.operations.FlsValidationRepresentation.addField(FlsValidationRepresentation.java:114);com.salesforce.rules.fls.apex.operations.SchemaBasedValidationAnalyzer.convert(SchemaBasedValidationAnalyzer.java:185);com.salesforce.rules.fls.apex.operations.SchemaBasedValidationAnalyzer.checkForValidation(SchemaBasedValidationAnalyzer.java:77)

Method code where the error occurs:

`
@RemoteAction 
    public static List<Map<String, Object>> getChildObjects(String parentObject) { 
        
        Map<String,String> sObjectIcons = getsObjectTabIcons();
        List<Map<String, Object>> childObjects = new List<Map<String, Object>>();
        List<String> objectNames = new List<String>{parentObject};
    
        Schema.DescribeSobjectResult objectDescribe = Schema.describeSObjects(objectNames, SObjectDescribeOptions.FULL)[0];
        for (Schema.ChildRelationship childRelationship: objectDescribe.getChildRelationships()) {
            if (childRelationship.getRelationshipName() != null) {
                Map<String, Object> childObject = new Map<String, Object>();
                Schema.DescribeSobjectResult childDescribe = childRelationship.getChildSObject().getDescribe();

                if (childDescribe.isQueryable()){
                    String sObjectName = childDescribe.getName();
                    String sObjectLabel = childDescribe.getLabel();
                    childObject.put('name', sObjectName);      
                    childObject.put('label', sObjectLabel);
                    childObject.put('childRelationship', childRelationship);
            
                    if (sObjectIcons.containsKey(sObjectName)){
                        String iconName = sObjectIcons.get(sObjectName);
                        childObject.put('icontype', iconName.substringBefore(':')); 
                        childObject.put('icon', iconName.substringAfter(':'));
                    }
            
                    childObjects.add(childObject);
                }
            }
        }
        
        return childObjects;
        
    } `
Steps To Reproduce:
I ran the following scanner:
sf scanner run dfa -f html -o QA/appexchange/CodeAnalyzerDFA.html -t './' -c 'Security' --projectdir='./'

Desktop:
Provide these details:

Operating System: Mac OS
Code Analyzer version: v3.20.0
Salesforce CLI version: @salesforce/cli/2.23.20 win32-x64 node-v18.19.0
Additional Context:

Workaround:
Tried the directives to exclude from the engine, but it doesn't work
Urgency:
Medium

**Comment by stephen-carter-at-sf** [comment] 2024-06-03 18:58
Marking this as a duplicate of https://github.com/forcedotcom/sfdx-scanner/issues/1497

**Closed by stephen-carter-at-sf** 2024-06-03 18:58 UTC
Labels: duplicate, BUG P3, SFGE
