### ISSUE TITLE
Github CI/CD Logic Scanner error: Error (1): A dynamic import callback was not specified. TypeError [ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING]: A dynamic import callback was not specified.

### ISSUE THREAD

**Issue by rosangelys-pfm** [forcedotcom/sfdx-scanner#1609] opened 2024-08-28 15:17 UTC
### Have you tried to resolve this issue yourself first?

Yes

### Bug Description

Hi! I am getting the following error when trying to run the sfdx scanner from my CI/CD logic. It was working fine last week, but when running today it failed with the following error:

(node:4516) Warning: Deprecated environment variable: SFDX_LAZY_LOAD_MODULES. Please use SF_LAZY_LOAD_MODULES instead.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4516) Warning: Deprecated environment variable: SFDX_AUTOUPDATE_DISABLE. Please use SF_AUTOUPDATE_DISABLE instead.
(node:45[16](https://github.com/Prison-Fellowship-Development/pfm-salesforce-crm/actions/runs/10599387655/job/29374301140?pr=90#step:14:17)) Warning: Deprecated environment variable: SFDX_DISABLE_AUTOUPDATE. Please use SF_DISABLE_AUTOUPDATE instead.
Warning: We're continually improving Salesforce Code Analyzer. Tell us what you think! Give feedback at https://research.net/r/SalesforceCA
Error (1): A dynamic import callback was not specified.
TypeError [ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING]: A dynamic import callback was not specified.
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:265:9)
    at LWCEslintStrategy.init (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/eslint/LWCEslintStrategy.js:43:101)
    at async LWCEslintEngine.init (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/eslint/EslintEngine.js:[19](https://github.com/Prison-Fellowship-Development/pfm-salesforce-crm/actions/runs/10599387655/job/29374301140?pr=90#step:14:20):9)
    at async Object.getAllEngines (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/Controller.js:47:13)
    at async LocalCatalog.init (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/services/LocalCatalog.js:51:24)
    at async DefaultRuleManager.init (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/DefaultRuleManager.js:63:9)
    at async Object.createRuleManager (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/Controller.js:36:9)
    at async RunAction.run (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/actions/AbstractRunAction.js:93:29)
    at async Run.run (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/ScannerCommand.js:38:16)
    at async Run._run (~/.local/share/sfdx/node_modules/@oclif/core/lib/command.js:311:[22](https://github.com/Prison-Fellowship-Development/pfm-salesforce-crm/actions/runs/10599387655/job/29374301140?pr=90#step:14:23))
Error: Process completed with exit code 1.

This is part of my logic:
`
- name: 'Create delta packages for new, modified or deleted metadata'
              run: |
                  mkdir changed-sources
                  sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output changed-sources/ --generate-delta --source force-app/ --ignore .sgdignore
                  cat ./changed-sources/**/package.xml
                  cat ./changed-sources/**/destructiveChanges.xml

            # Prettier formatting check
            - name: 'Code formatting check with Prettier'
              run: |
                  cd changed-sources
                  npx prettier --list-different './**/*.{apex,cls,cmp,component,css,html,js,json,trigger}' --ignore-unknown --no-error-on-unmatched-pattern

            # Now we can use the sfdx scanner to scan the code in the delta directory
            # The output of the scan is stored in a file called apexScanResults.csv

            # Check if cls files are present in the changed sources directory.
            - name: 'Check CLS file existence'
              id: check_files
              uses: andstor/file-existence-action@v3
              with:
                  files: 'changed-sources/**/*.cls'

            # The .xml file can later be uploaded to github, so that we can see the
            # results of the scan directly from the PR.
            - name: 'Scan code'
              id: scan-results
              if: steps.check_files.outputs.files_exists == 'true'
              run: |
                cd changed-sources
                sfdx scanner:run --format csv --target './**/*.cls' --projectdir './' --severity-threshold 3 --outfile 'apexScanResults.csv'  
                cd ..          
`

### Output / Logs

(node:4516) Warning: Deprecated environment variable: SFDX_LAZY_LOAD_MODULES. Please use SF_LAZY_LOAD_MODULES instead.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4516) Warning: Deprecated environment variable: SFDX_AUTOUPDATE_DISABLE. Please use SF_AUTOUPDATE_DISABLE instead.
(node:45[16](https://github.com/Prison-Fellowship-Development/pfm-salesforce-crm/actions/runs/10599387655/job/29374301140?pr=90#step:14:17)) Warning: Deprecated environment variable: SFDX_DISABLE_AUTOUPDATE. Please use SF_DISABLE_AUTOUPDATE instead.
Warning: We're continually improving Salesforce Code Analyzer. Tell us what you think! Give feedback at https://research.net/r/SalesforceCA
Error (1): A dynamic import callback was not specified.
TypeError [ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING]: A dynamic import callback was not specified.
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:265:9)
    at LWCEslintStrategy.init (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/eslint/LWCEslintStrategy.js:43:101)
    at async LWCEslintEngine.init (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/eslint/EslintEngine.js:[19](https://github.com/Prison-Fellowship-Development/pfm-salesforce-crm/actions/runs/10599387655/job/29374301140?pr=90#step:14:20):9)
    at async Object.getAllEngines (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/Controller.js:47:13)
    at async LocalCatalog.init (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/services/LocalCatalog.js:51:24)
    at async DefaultRuleManager.init (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/DefaultRuleManager.js:63:9)
    at async Object.createRuleManager (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/Controller.js:36:9)
    at async RunAction.run (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/actions/AbstractRunAction.js:93:29)
    at async Run.run (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/ScannerCommand.js:38:16)
    at async Run._run (~/.local/share/sfdx/node_modules/@oclif/core/lib/command.js:311:[22](https://github.com/Prison-Fellowship-Development/pfm-salesforce-crm/actions/runs/10599387655/job/29374301140?pr=90#step:14:23))
Error: Process completed with exit code 1.

### Steps To Reproduce

1. Run sfdx scanner from CI/CD pipeline on GitHub xml file

### Expected Behavior

SFDX Scanner will scan the files on the target source 

### Operating System

Github Workflow VM:  Ubuntu   22.04.4   LTS

### Salesforce CLI Version

sfdx-cli@47.15.1

### Code Analyzer Plugin (@salesforce/sfdx-scanner) Version

@salesforce/sfdx-scanner (latest)

### Urgency

High

**Comment by feernandobraga** [comment] 2024-08-29 01:13
Our pipeline is also being impacted by what seems to be the same issue:
```
Run cd changed-sources
(node:4272) Warning: Deprecated environment variable: SFDX_LAZY_LOAD_MODULES. Please use SF_LAZY_LOAD_MODULES instead.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4272) Warning: Deprecated environment variable: SFDX_AUTOUPDATE_DISABLE. Please use SF_AUTOUPDATE_DISABLE instead.
(node:4272) Warning: Deprecated environment variable: SFDX_DISABLE_AUTOUPDATE. Please use SF_DISABLE_AUTOUPDATE instead.
Warning: We're continually improving Salesforce Code Analyzer. Tell us what you think! Give feedback at https://research.net/r/SalesforceCA
Error (1): A dynamic import callback was not specified.
TypeError [ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING]: A dynamic import callback was not specified.
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:265:9)
    at LWCEslintStrategy.init (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/eslint/LWCEslintStrategy.js:43:101)
    at async LWCEslintEngine.init (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/eslint/EslintEngine.js:19:9)
    at async Object.getAllEngines (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/Controller.js:47:13)
    at async LocalCatalog.init (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/services/LocalCatalog.js:51:24)
    at async DefaultRuleManager.init (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/DefaultRuleManager.js:63:9)
    at async Object.createRuleManager (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/Controller.js:36:9)
    at async RunAction.run (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/actions/AbstractRunAction.js:92:29)
    at async Run.run (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/ScannerCommand.js:3[8](https://github.com/VGW/cam-servicecloud/actions/runs/10606753543/job/29398056189?pr=425#step:12:9):16)
    at async Run._run (~/.local/share/sfdx/node_modules/@oclif/core/lib/command.js:311:22)
Error: Process completed with exit code 1.
```

**Comment by PadyHub** [comment] 2024-08-29 01:19
**Bumping up, same issue as highlighted above, more than 5 users are impacted by this issue...** 
`Run cd changed-sources
  cd changed-sources
  sfdx scanner:run --format sarif --target './**/*.cls' --category "Design,Best Practices,Performance" --outfile 'apexScanResults.sarif'  
  cd ..
  shell: /usr/bin/bash -e {0}
  env:
    APEX_TESTS: all
(node:4[2](https://github.com/VGW/cam-servicecloud/actions/runs/10606753543/job/29398056189?pr=425#step:12:2)72) Warning: Deprecated environment variable: SFDX_LAZY_LOAD_MODULES. Please use SF_LAZY_LOAD_MODULES instead.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4272) Warning: Deprecated environment variable: SFDX_AUTOUPDATE_DISABLE. Please use SF_AUTOUPDATE_DISABLE instead.
(node:4272) Warning: Deprecated environment variable: SFDX_DISABLE_AUTOUPDATE. Please use SF_DISABLE_AUTOUPDATE instead.
Warning: We're continually improving Salesforce Code Analyzer. Tell us what you think! Give feedback at https://research.net/r/SalesforceCA
Error (1): A dynamic import callback was not specified.
TypeError [ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING]: A dynamic import callback was not specified.
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:265:9)
    at LWCEslintStrategy.init (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/eslint/LWCEslintStrategy.js:4[3](https://github.com/VGW/cam-servicecloud/actions/runs/10606753543/job/29398056189?pr=425#step:12:3):101)
    at async LWCEslintEngine.init (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/eslint/EslintEngine.js:19:9)
    at async Object.getAllEngines (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/Controller.js:[4](https://github.com/VGW/cam-servicecloud/actions/runs/10606753543/job/29398056189?pr=425#step:12:4)7:13)
    at async LocalCatalog.init (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/services/LocalCatalog.js:[5](https://github.com/VGW/cam-servicecloud/actions/runs/10606753543/job/29398056189?pr=425#step:12:5)1:24)
    at async DefaultRuleManager.init (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/DefaultRuleManager.js:[6](https://github.com/VGW/cam-servicecloud/actions/runs/10606753543/job/29398056189?pr=425#step:12:6)3:9)
    at async Object.createRuleManager (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/Controller.js:36:9)
    at async RunAction.run (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/actions/AbstractRunAction.js:92:29)
    at async Run.run (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/ScannerCommand.js:3[8](https://github.com/VGW/cam-servicecloud/actions/runs/10606753543/job/29398056189?pr=425#step:12:9):16)
    at async Run._run (~/.local/share/sfdx/node_modules/@oclif/core/lib/command.js:311:22)
Error: Process completed with exit code 1.`

**Comment by Monikag555** [comment] 2024-08-29 11:44
Encountering the same issue as mentioned. This is the issue that is encountering while running the GitHub workflow. I tried of changing the Node Version, updated the SFDX plugin as well but still it was not yet resolved. 

Run sfdx scanner:run --target "force-app/main/default/classes,force-app/main/default/lwc" --format "csv" --outfile "scanner-report.csv"
(node:2000) Warning: Deprecated environment variable: SFDX_LAZY_LOAD_MODULES. Please use SF_LAZY_LOAD_MODULES instead.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2000) Warning: Deprecated environment variable: SFDX_AUTOUPDATE_DISABLE. Please use SF_AUTOUPDATE_DISABLE instead.
(node:2000) Warning: Deprecated environment variable: SFDX_DISABLE_AUTOUPDATE. Please use SF_DISABLE_AUTOUPDATE instead.
Warning: We're continually improving Salesforce Code Analyzer. Tell us what you think! Give feedback at https://research.net/r/SalesforceCA
Error (1): A dynamic import callback was not specified.
TypeError [ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING]: A dynamic import callback was not specified.
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:265:9)
    at LWCEslintStrategy.init (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/eslint/LWCEslintStrategy.js:[4](https://github.com/Monikag555/SATS-Application/actions/runs/10613136059/job/29416319363#step:8:5)3:101)
    at async LWCEslintEngine.init (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/eslint/EslintEngine.js:19:9)
    at async Object.getAllEngines (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/Controller.js:47:13)
    at async LocalCatalog.init (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/services/LocalCatalog.js:[5](https://github.com/Monikag555/SATS-Application/actions/runs/10613136059/job/29416319363#step:8:6)1:24)
    at async DefaultRuleManager.init (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/DefaultRuleManager.js:[6](https://github.com/Monikag555/SATS-Application/actions/runs/10613136059/job/29416319363#step:8:7)3:9)
    at async Object.createRuleManager (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/Controller.js:36:9)
    at async RunAction.run (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/actions/AbstractRunAction.js:93:29)
    at async Run.run (~/.local/share/sfdx/node_modules/@salesforce/sfdx-scanner/lib/lib/ScannerCommand.js:3[8](https://github.com/Monikag555/SATS-Application/actions/runs/10613136059/job/29416319363#step:8:9):16)
    at async Run._run (~/.local/share/sfdx/node_modules/@oclif/core/lib/command.js:311:22)
Error: Process completed with exit code 1.

**Comment by stephen-carter-at-sf** [comment] 2024-08-29 14:04
Hello all. Our team is looking into this now... will let you know what we find.

**Comment by stephen-carter-at-sf** [comment] 2024-08-29 14:09
Is anyone experiencing this issue with `sf` or are you all using the old `sfdx` ?

Our best guess so far is that the issue is a result of the use of an outdated version of the salesforce cli.

Please update to latest `sf` command with:
```
npm install -g @salesforce/cli@latest
```
and use `sf scanner` instead of `sfdx scanner`.

Also, note that for CI/CD pipelines inside of github, we recommend you checkout the [Run Code Analyzer - GitHub Action](https://github.com/forcedotcom/run-code-analyzer).

Can someone who is experiencing this issue... give this a try and see if it fixes your problem?

**Comment by stephen-carter-at-sf** [comment] 2024-08-29 16:36
Given that [sfdx has been deprecated](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference.htm#:~:text=The%20sfdx%20%2Dstyle%20commands%20are,bug%20fixes%2C%20or%20technical%20support) has no longer has support since April 2023... I will close this issue.

If someone sees this issue with code analyzer with the `sf` cli, then please reopen this issue.

**Closed by stephen-carter-at-sf** 2024-08-29 16:36 UTC
Labels: Need more info
